### ISSUE TITLE
Kusamu  finalized block  will not change for a period of time

### ISSUE THREAD

**Issue by zhy827827** [paritytech/polkadot#7254] opened 2023-05-19 02:30 UTC
i use docker deloyment kusama arhive node:
`sudo docker run -d -p 19944:9944 -p 19933:9933 --network=hostksm --name ksmarchive -v /opt/kusuma/data:/polkadot parity/polkadot:v0.9.42 --rpc-external --ws-external --chain kusama --rpc-cors all --pruning archive`

i find issues,sometimes Kusama has been in the same block in Finalized.At most, the same block is in 20 minutes

![1684460020064](https://github.com/paritytech/polkadot/assets/15209848/230f04d3-4a82-4d2b-b7a4-6da4bfe05953)

**Comment by altonen** [comment] 2023-05-19 04:38
Duplicate of https://github.com/paritytech/polkadot/issues/7240

**Closed by altonen** 2023-05-19 04:38 UTC
