### ISSUE TITLE
Externalities not allowed to fail within runtime

### ISSUE THREAD

**Issue by tonychew1986** [paritytech/polkadot#448] opened 2019-09-26 06:59 UTC
Encountered the following issues:  

15: wasmi::func::FuncInstance::invoke::h4c7836e8df7b51f0 (0x55b8f1f34dad)
16: std::thread::local::LocalKey<T>::with::hd0c5c282b4eb4788 (0x55b8f1fcf596)
17: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::h01584f35164c2eaf (0x55b8f1deb316)
18: std::thread::local::LocalKey<T>::with::hd505a32ce034f571 (0x55b8f1ffd576)
19: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux::hc9b9d4527a2ce0e5 (0x55b8f21b3203)
20: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler::h506af393d4f915dc (0x55b8f21d8762)
21: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hac5b997fe079aa2d (0x55b8f20ed4fc)
22: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h72aa56d42d8f683d (0x55b8f2482456)
23: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at::h247caead11373613 (0x55b8f1edfe72)
24: substrate_client::runtime_api::Core::initialize_block::h8cf881f03f50c667 (0x55b8f1f7bee6)
25: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h3e31bdbad01def91 (0x55b8f20e5b74)
26: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h24304cf5d630c56c (0x55b8f24803e9)
27: substrate_consensus_babe_primitives::runtime_decl_for_BabeApi::epoch_call_api_at::h0c513c0a7be7d5a9 (0x55b8f1df6c7e)
28: substrate_consensus_babe_primitives::BabeApi::epoch::h86766ec08ff29deb (0x55b8f1fc004a)
29: substrate_consensus_babe::epoch_from_runtime::h00bd6d5d8dd93f95 (0x55b8f22afe8e)
30: <substrate_consensus_babe::BabeVerifier<B,E,Block,RA,PRA,T> as substrate_consensus_common::import_queue::Verifier<Block>>::verify::h2f8f2a962fdb5cc6 (0x55b8f2279bf1)
31: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h70330685c463b576 (0x55b8f24ec7fe)
32: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll::ha0a135c417d5cc03 (0x55b8f1f55fc6)
33: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll::h2bb6a2f6b22a9758 (0x55b8f24eb648)
34: futures_executor::thread_pool::PoolState::work::h760549ccfb812f25 (0x55b8f2f98486)
35: std::sys_common::backtrace::__rust_begin_short_backtrace::hdd5adc06db61bf86 (0x55b8f2f9a3c4)
36: std::panicking::try::do_call::h0b9f29ad5793018b (0x55b8f2f957b5)
37: __rust_maybe_catch_panic (0x55b8f315bada)
             at src/libpanic_unwind/lib.rs:82
38: core::ops::function::FnOnce::call_once{{vtable.shim}}::hd2885eaa11a4176a (0x55b8f2f9741a)
39: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h56322f6b657cd33d (0x55b8f314097f)
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/liballoc/boxed.rs:766
40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h2cbeedc59f1a5bf0 (0x55b8f315ae60)
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/liballoc/boxed.rs:766
      std::sys_common::thread::start_thread::h780c24dc0e8bc388
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h588aedefb535eac7
             at src/libstd/sys/unix/thread.rs:79
41: start_thread (0x7f2025acc6db)
42: __clone (0x7f20255dd88f)
43: <unknown> (0x0)

Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x7560eb51181955d4f524ecd2bd03efd84db21c12e3a86cef5303b97ae58996d8"', src/libcore/result.rs:1051

**Comment by bkchr** [comment] 2019-09-26 07:38
Duplicate of https://github.com/paritytech/polkadot/issues/419

**Closed by bkchr** 2019-09-26 07:38 UTC
