### ISSUE TITLE
v0.9.7 crash "Signal channel is terminated and empty."

### ISSUE THREAD

**Issue by SimonKraus** [paritytech/polkadot#3374] opened 2021-06-25 22:05 UTC
After upgrading to v0.9.7 my Kusama node was running fine but after some time it crashed with the following messages:
```
Jun 25 21:41:04 hydraserver polkadot[855773]: 2021-06-25 21:41:04 err=Subsystem(Context("Signal channel is terminated and empty."))

Jun 25 21:41:04 hydraserver polkadot[855773]: 2021-06-25 21:41:04 Shutting down Network Bridge due to error err=Context("Signal channel is terminated and empty.")

Jun 25 21:41:04 hydraserver polkadot[855773]: 2021-06-25 21:41:04 error receiving message from subsystem context: Context("Signal channel is terminated and empty.") err=Context("Signal channel is terminated and empty.")

Jun 25 21:41:04 hydraserver polkadot[855773]: 2021-06-25 21:41:04 subsystem exited with error subsystem="network-bridge-subsystem" err=FromOrigin { origin: "network-bridge", source: Context("Received SubsystemError from overseer: Context("Signal channel is terminated and empty.")") }

Jun 25 21:41:04 hydraserver polkadot[855773]: 2021-06-25 21:41:04 Essential task overseer failed. Shutting down service.

Jun 25 21:41:04 hydraserver polkadot[855773]: 2021-06-25 21:41:04 subsystem exited with error subsystem="statement-distribution-subsystem" err=FromOrigin { origin: "statement-distribution", source: SubsystemReceive(Context("Signal channel is terminated and empty.")) }

Jun 25 21:41:04 hydraserver polkadot[855773]: 2021-06-25 21:41:04 subsystem exited with error subsystem="runtime-api-subsystem" err=Context("Signal channel is terminated and empty.")
```

I restarted the node. It seemed running but was stuck on the same block (#8073544).
The server vitals were fine.

Hardware: AMD 5950x, 128gb ram, samsung evo 980 pro
OS: Ubuntu Server 20.04 LTS

I downgraded back to 0.9.6 and synced up the chain.
Then I went back to 0.9.7 and now it seems to run stable.

Will report back if it crashes again. It's probably not worth looking into as I coudn't spot any other stuck 0.9.7 nodes in the telemetries.

**Comment by ordian** [comment] 2021-06-25 22:30
duplicate of #3242

**Closed by ordian** 2021-06-25 22:30 UTC
