### ISSUE TITLE
Memory leak in disputes

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#3664] opened 2021-08-19 11:38 UTC
It looks like received dispute messages pile up in memory somewhere. As can be seen here:
![dispute distribution](https://user-images.githubusercontent.com/1527017/130062165-1810ced8-69c3-439e-a462-e8b7cf9352d2.png).

@koute 

Open questions:

- Does it scale with the number of validators?
- Can it be fixed by switching to paritydb?

**Comment by koute** [comment] 2021-08-23 08:27
This is from a validator node which ran for ~6.5h and then suddenly started to leak, and was killed due to running out of memory.

(Note: all of the following graphs are missing short lived allocations with lifetime of less than 10 seconds.)

First, here's the memory usage graph:

![01_memory_usage](https://user-images.githubusercontent.com/246574/130414258-eecace01-ac88-42ad-bfb9-b526936e0667.png)

And here's a breakdown of the leaked part:

![02_leaked_decomposition](https://user-images.githubusercontent.com/246574/130414386-2b2ea87c-60b4-44c3-949e-65e0d36d3ac9.png)

Here are the channels' metrics from that time:

![channels](https://user-images.githubusercontent.com/246574/130415092-09990615-b4a8-4579-8632-31a14b245d1f.png)

Around that time allocations from the following subsystems got sparse:

![03_quiet_subsystems_1](https://user-images.githubusercontent.com/246574/130415146-7757ff14-ce8b-49d2-a211-485382044ccc.png)

![04_quiet_subsystems_2](https://user-images.githubusercontent.com/246574/130415158-c67c15a1-8875-4f1b-a22e-00f5ce6ba27c.png)

And a lot of votes were being handled:

![05_handle_vote](https://user-images.githubusercontent.com/246574/130415172-78189c6f-b833-41e2-9e59-1549f2ed54ff.png)

**Comment by eskimor** [comment] 2021-08-23 08:39
Thanks a lot @koute for this in depth analysis!

**Comment by expenses** [comment] 2021-08-23 14:48
Is this an issue that we'd be able to reproduce somehow? Then we could do a git bisect to find the commit that introduced the leak.

**Comment by rphmeier** [comment] 2021-08-23 15:52
I expect you'd be able to reproduce it by running a network with nodes compiled with `features=disputes and at least one parachain activated.

**Comment by expenses** [comment] 2021-08-23 16:29
Is this guide: https://github.com/paritytech/cumulus#launch-a-local-setup-including-a-relay-chain-and-a-parachain still up-to-date on how to do this?

**Comment by tomaka** [comment] 2021-08-23 16:40
If this is one of our nodes, can we maybe have the node name and the time when it happened? This way we can look at Parity's Grafana instance.

**Comment by expenses** [comment] 2021-08-24 15:22
As I am not part of devops, I feel like the amount of work I can do to work out this issue is limited.

**Comment by koute** [comment] 2021-09-06 09:54
So I've been fiddling around with trying to reproduce this issue; I *think* I might have something here. I've just launched a local ~250 node testnet (with my [polkadot-starship](https://github.com/koute/polkadot-starship)) and got something similar to what we've seen in the wild, that is a bunch of disputes being sent:

![dispute](https://user-images.githubusercontent.com/246574/132197870-34e2ac10-ce20-4921-b33b-a2a0be07f666.png)

and also a significant finality lag.

So for now I'm assigning this issue to myself and I'll try to poke and prod it even more.

**Comment by ordian** [comment] 2021-09-06 10:30
@koute awesome, let me know if you need any help. Could you also check if it's reproducible with master after #3753?

**Comment by koute** [comment] 2021-09-06 10:34
> @koute awesome, let me know if you need any help. Could you also check if it's reproducible with master after #3753?

Thanks for letting me know about that PR! Once I'm sure I can reproduce it reliably I'll definitely check.

**Comment by ordian** [comment] 2022-08-16 16:58
I believe this has been fixed already.

**Closed by ordian** 2022-08-16 16:58 UTC
Labels: F2-bug
