### ISSUE TITLE
Node not starting with paritydb

### ISSUE THREAD

**Issue by hirschenberger** [paritytech/polkadot#2898] opened 2021-04-17 12:54 UTC
```
❯ RUST_BACKTRACE=1 cargo run --release --  --chain=polkadot --database=paritydb-experimental
    Finished release [optimized] target(s) in 0.53s
     Running `target/release/polkadot --chain=polkadot --database=paritydb-experimental --name hirschenberger`
2021-04-17 14:47:19  Parity Polkadot
2021-04-17 14:47:19  ✌️  version 0.8.30-fff63cb50-x86_64-linux-gnu
2021-04-17 14:47:19  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-04-17 14:47:19  📋 Chain specification: Polkadot
2021-04-17 14:47:19  🏷 Node name: future-shoe-6322
2021-04-17 14:47:19  👤 Role: FULL
2021-04-17 14:47:19  💾 Database: ParityDb at /home/hirschen/.local/share/polkadot/chains/polkadot/paritydb
2021-04-17 14:47:19  ⛓  Native runtime: polkadot-31 (parity-polkadot-0.tx7.au0)
Error:
   0: Backend error: Invalid configuration: Column config mismatch for column 1. Expected "preimage: false, uniform: false, refc: false, sizes: [96, 128, 192, 256, 320, 512, 768, 1024, 1536, 2048, 3072, 4096, 8192, 16384, 32768]", got "preimage: true, uniform: true, refc: true, sizes: [96, 128, 192, 256, 320, 512, 768, 1024, 1536, 2048, 3072, 4096, 8192, 16384, 32768]"

Location:
   src/main.rs:25
```
`cargo 1.52.0-nightly (90691f2bf 2021-03-16)`

Works with `--light` node parameter.

**Comment by ordian** [comment] 2021-04-17 13:40
To reproduce:
```
cargo run --release -- purge-chain --database=paritydb-experimental
cargo run --release -- --light --database=paritydb-experimental
cargo run --release -- --database=paritydb-experimental
```
The problem is light and full dbs are stored in the same folder, shouldn't we store them separately?

**Comment by hirschenberger** [comment] 2021-04-17 14:04
And maybe `purge-chain` should purge all chains, atm it doesn't purge the partitydb if you don't pass the `--database=paritydb-experimental` parameter. 
That's what confused me, bc. I issued purge-chain multiple times and thought I have a clean env.

**Comment by bkchr** [comment] 2021-04-17 14:59
Duplicate of https://github.com/paritytech/substrate/issues/6880

**Closed by bkchr** 2021-04-17 14:59 UTC
Labels: F2-bug
