### ISSUE TITLE
Validator nodes stop syncing on v0.9.41

### ISSUE THREAD

**Issue by aperture-sandi** [paritytech/polkadot#7062] opened 2023-04-12 15:23 UTC
Several reports of validator node syncing issues in matrix groups. 

Users report…
My node again keeps falling behind after upgrading to v0.9.41 (log below)
```
Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x5c719d0672742f3888b8eee9324f708a92f81767d2ec4bb5b4c6653ccb2967e3 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x5c719d0672742f3888b8eee9324f708a92f81767d2ec4bb5b4c6653ccb2967e3 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x5c719d0672742f3888b8eee9324f708a92f81767d2ec4bb5b4c6653ccb2967e3 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x5c719d0672742f3888b8eee9324f708a92f81767d2ec4bb5b4c6653ccb2967e3 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x5c719d0672742f3888b8eee9324f708a92f81767d2ec4bb5b4c6653ccb2967e3 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x6c92652bacaa66560dfe9679712d5ec603b1f0e810f6db3099153fed4c8a1e50 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x5c719d0672742f3888b8eee9324f708a92f81767d2ec4bb5b4c6653ccb2967e3 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x5c719d0672742f3888b8eee9324f708a92f81767d2ec4bb5b4c6653ccb2967e3 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x6c92652bacaa66560dfe9679712d5ec603b1f0e810f6db3099153fed4c8a1e50 Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x64e876cd1e5ee558b34ada9866c78b5b03efc220ee43288c86fa8dfa780bf3be Apr 06 14:29:13 kusama-2 polkadot[174432]: 2023-04-06 14:29:13 error=Runtime(RuntimeRequest(NotSupported { runtime_api_name: "session_info" })) Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:15 kusama-2 polkadot[174432]: 2023-04-06 14:29:15 Accepting new connection 1/100 Apr 06 14:29:16 kusama-2 polkadot[174432]: 2023-04-06 14:29:16 cannot query the runtime API version: Api called for an unknown Block: Header was not found in the database: 0x64e876cd1e5ee558b34ada9866c78b5b03efc220ee43288c86fa8dfa780bf3be Apr 06 14:29:16 kusama-2 polkadot[174432]: 2023-04-06 14:29:16 error=Runtime(RuntimeRequest(NotSup
```

Another users states…
“My validator got chilled with errors like these. (Above) Node was on 0.9.41 rocksdb”

**Comment by sandreim** [comment] 2023-04-12 15:50
Duplicate of https://github.com/paritytech/polkadot/issues/7021

**Closed by sandreim** 2023-04-12 15:50 UTC
