### ISSUE TITLE
Attempt to connect telemetry, ignoring options

### ISSUE THREAD

**Issue by chevdor** [paritytech/polkadot#329] opened 2018-07-16 07:54 UTC
`$ target/release/polkadot --chain poc-1`

results in:

```
Connected to telemetry server: ws://telemetry.polkadot.io:1024
Error: Failed to parse network address
```

**Comment by tomaka** [comment] 2018-07-16 08:01
> Error: Failed to parse network address

That's not caused by telemetry but by the fact that the PoC-1 bootstrap nodes addresses are no longer valid.

**Comment by iammelea** [comment] 2018-07-16 23:39
Solution?

**Comment by gavofyork** [comment] 2018-07-17 07:14
Once that's merged, it'll go away :)

**Closed** 2018-07-17 08:10 UTC
