### ISSUE TITLE
panic: supplied instant is later than self

### ISSUE THREAD

**Issue by pepyakin** [paritytech/polkadot#849] opened 2020-02-17 12:34 UTC
```
====================

Version: 0.7.20-a6164235-x86_64-macos

stack backtrace:
   0: backtrace::backtrace::trace
   1: backtrace::capture::Backtrace::new
   2: sp_panic_handler::set::{{closure}}
   3: std::panicking::rust_panic_with_hook
   4: rust_begin_unwind
   5: core::panicking::panic_fmt
   6: core::option::expect_failed
   7: std::time::Instant::duration_since
   8: <std::time::Instant as core::ops::arith::Sub>::sub
   9: <sc_network::protocol::legacy_proto::behaviour::LegacyProto<TSubstream> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  10: <sc_network::protocol::Protocol<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  11: <sc_network::behaviour::Behaviour<B,S,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  12: libp2p_swarm::ExpandedSwarm<TTransport,TBehaviour,TInEvent,TOutEvent,THandler,THandlerErr,TConnInfo>::poll_next_event
  13: futures_util::future::future::FutureExt::poll_unpin
  14: <sc_network::service::NetworkWorker<B,S,H> as core::future::future::Future>::poll
  15: futures_util::future::future::FutureExt::poll_unpin
  16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  17: <futures_util::future::future::map::Map<Fut,F> as core::future::future::Future>::poll
  18: tokio::task::core::Core<T>::poll
  19: std::panicking::try::do_call
  20: __rust_maybe_catch_panic
  21: tokio::task::harness::Harness<T,S>::poll
  22: tokio::runtime::thread_pool::worker::GenerationGuard::run_task
  23: tokio::runtime::thread_pool::worker::GenerationGuard::run
  24: std::thread::local::LocalKey<T>::with
  25: tokio::runtime::thread_pool::worker::Worker::run
  26: tokio::task::core::Core<T>::poll
  27: std::panicking::try::do_call
  28: __rust_maybe_catch_panic
  29: tokio::task::harness::Harness<T,S>::poll
  30: tokio::runtime::blocking::pool::Inner::run
  31: tokio::runtime::context::enter
  32: std::sys_common::backtrace::__rust_begin_short_backtrace
  33: std::panicking::try::do_call
  34: __rust_maybe_catch_panic
  35: core::ops::function::FnOnce::call_once{{vtable.shim}}
  36: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
  37: std::sys::unix::thread::Thread::new::thread_start
  38: _pthread_start


Thread 'main-tokio-' panicked at 'supplied instant is later than self', src/libcore/option.rs:1188
```

before the crash the log had this

```
2020-02-17 11:48:49 Imported #1078429 (0x9b85…fa76)
2020-02-17 11:48:52 Idle (22 peers), best: #1078429 (0x9b85…fa76), finalized #1078426 (0x3d7b…de56), ⬇ 10.1kiB/s ⬆ 3.6kiB/s
2020-02-17 11:48:54 Imported #1078430 (0x6965…600d)
2020-02-17 11:55:55 Idle (22 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 19.4kiB/s ⬆ 27.3kiB/s
2020-02-17 11:56:00 Idle (22 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 7.0kiB/s ⬆ 7.2kiB/s
2020-02-17 11:56:05 Idle (22 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.1kiB/s ⬆ 0.2kiB/s
2020-02-17 11:56:10 Idle (22 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.5kiB/s ⬆ 0.6kiB/s
2020-02-17 11:56:14 d4ce462a: socket error: decode error: i/o error: Operation timed out (os error 60)
2020-02-17 11:56:15 Idle (16 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.3kiB/s ⬆ 5.9kiB/s
2020-02-17 11:56:20 Idle (9 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.6kiB/s ⬆ 0.6kiB/s
2020-02-17 11:56:22 7998f1d2: socket error: decode error: i/o error: Operation timed out (os error 60)
2020-02-17 11:56:25 Idle (2 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.7kiB/s ⬆ 0.7kiB/s
2020-02-17 11:56:31 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.7kiB/s ⬆ 0.7kiB/s
2020-02-17 11:56:35 Disconnected from /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Sink(Custom { kind: Other, error: B(Custom { kind: Other, error: Closed }) })
2020-02-17 11:56:36 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.2kiB/s ⬆ 0.2kiB/s
2020-02-17 11:57:26 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 11:57:27 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 11:57:31 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 11:57:36 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 11:57:36 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 11:57:41 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 11:57:41 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 11:57:46 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 11:57:46 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:12:29 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:12:30 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:12:34 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0.3kiB/s ⬆ 0.3kiB/s
2020-02-17 12:12:39 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:12:39 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:12:44 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:12:47 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:12:49 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:12:54 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:12:54 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:12:59 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:13:01 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:13:04 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:14:26 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:14:28 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:14:31 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:14:33 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:14:38 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:14:40 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:14:43 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:14:45 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:14:48 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:14:53 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
2020-02-17 12:14:54 Error while dialing /dns4/telemetry.polkadot.io/tcp/443/x-parity-wss/%2Fsubmit%2F: Custom { kind: Other, error: Other(B(A(Transport(ResolveError { domain_name: "telemetry.polkadot.io", error: Custom { kind: Other, error: "failed to lookup address information: nodename nor servname provided, or not known" } })))) }
2020-02-17 12:14:58 Idle (0 peers), best: #1078430 (0x6965…600d), finalized #1078427 (0x1a41…f4a4), ⬇ 0 ⬆ 0
```

cc @tomaka since this seems to come from network/libp2p

**Comment by tomaka** [comment] 2020-02-17 12:42
Duplicate of https://github.com/paritytech/substrate/issues/4949

**Closed by tomaka** 2020-02-17 12:42 UTC
Labels: F1-panic
