### ISSUE TITLE
Database missing expected key

### ISSUE THREAD

**Issue by andreafspeziale** [paritytech/polkadot#6415] opened 2022-12-09 10:03 UTC
Hello everyone and thanks for your hard work. I'm running a Kusama node and found the following error suggesting me to open an issue:

```
Version: 0.9.33-c7d6c21242f

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
   4: rust_begin_unwind
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
   5: core::panicking::panic_fmt
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
   6: core::result::unwrap_failed
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
   7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
   8: sp_io::storage::get_version_1
   9: sp_io::storage::ExtStorageGetVersion1::call
  10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: wasmtime_runtime::traphandlers::catch_traps::call_closure
  16: wasmtime_setjmp
  17: sc_executor_wasmtime::runtime::perform_call
  18: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
  19: sc_executor_common::wasm_runtime::WasmInstance::call_export
  20: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
  21: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
  22: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
  23: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
  24: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
  25: sp_authority_discovery::AuthorityDiscoveryApi::authorities
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::run::{{closure}}
  28: tokio::runtime::task::harness::poll_future
  29: tokio::runtime::task::raw::poll
  30: tokio::runtime::thread_pool::worker::Context::run_task
  31: tokio::runtime::thread_pool::worker::run
  32: tokio::runtime::task::raw::poll
  33: std::sys_common::backtrace::__rust_begin_short_backtrace
  34: core::ops::function::FnOnce::call_once{{vtable.shim}}
  35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
  36: start_thread
  37: clone


Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x259e172b790e37cf987ec055e8737fe4f328ed219faaecac64c976c1d10aacf2"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/2dff067/primitives/state-machine/src/ext.rs:189

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
```

Since it was happening again and again lately the only thing I've tried was restoring the db from one of the latest snapshot provided by `polkashots`.

The only solution that I believe could work would be resync from scratch spending some days on it.

Thanks in advance.

**Comment by bkchr** [comment] 2022-12-09 10:10
Duplicate of: https://github.com/paritytech/polkadot/issues/6377

**Closed by bkchr** 2022-12-09 10:10 UTC
