### ISSUE TITLE
Tokio-runtime-worker - panicked in Version 0.8.27

### ISSUE THREAD

**Issue by yancaitech** [paritytech/polkadot#2278] opened 2021-01-16 17:32 UTC
0.8.26 ok
0.8.27 panic

OS: Windows 10 - WSL - Ubuntu 20.04 LTS

====================

Version: 0.8.27-5649a8a1-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495
   5: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   9: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  10: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
  11: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  12: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  19: std::thread::local::LocalKey<T>::with
  20: futures_executor::local_pool::block_on
  21: tokio::runtime::task::core::Core<T,S>::poll
  22: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  23: tokio::runtime::task::harness::Harness<T,S>::poll
  24: tokio::runtime::blocking::pool::Inner::run
  25: tokio::runtime::context::enter
  26: std::sys_common::backtrace::__rust_begin_short_backtrace
  27: core::ops::function::FnOnce::call_once{{vtable.shim}}
  28: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71
  29: start_thread
  30: clone

Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /home/dell/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix/linux.rs:107

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

**Comment by bkchr** [comment] 2021-01-16 23:34
Duplicate of https://github.com/paritytech/substrate/issues/7794

**Closed by bkchr** 2021-01-16 23:34 UTC
