### ISSUE TITLE
Flaky or broken zombienet tests

### ISSUE THREAD

**Issue by bkchr** [paritytech/polkadot#5243] opened 2022-04-03 18:41 UTC
https://gitlab.parity.io/parity/polkadot/-/jobs/1474913

I have also seen some other test being red, but I'm not sure if they are just flaky or broken.

Would be nice if someone could take a look.

CC @pepoviola @sandreim

**Comment by bkchr** [comment] 2022-04-03 18:55
https://gitlab.parity.io/parity/polkadot/-/jobs/1475207

https://gitlab.parity.io/parity/polkadot/-/jobs/1475205

**Comment by sandreim** [comment] 2022-04-03 19:01
The k8s pod deployment times out, probably it is scaling up. We should do some experiments and see how much it takes for a new k8s node to boot and join the cluster and use that as a default timeout in zombienet.

**Comment by bkchr** [comment] 2022-04-03 19:04
What kind of timeout is that? What does it ensures?

**Comment by sandreim** [comment] 2022-04-03 19:25
This one, but seems already bumped to 300 in master - https://github.com/paritytech/zombienet/blob/main/src/providers/k8s/kubeClient.ts#L56

The timeout ensures the pod is either running or has finished execution 
- https://github.com/paritytech/zombienet/blob/main/src/providers/k8s/kubeClient.ts#L186

We are sitting on an older version with only 60s timeout (https://github.com/paritytech/polkadot/blob/master/.gitlab-ci.yml#L35)

**Comment by bkchr** [comment] 2022-04-03 19:29
Okay, isn't there a way of subscribe on the status of a pod?

**Comment by sandreim** [comment] 2022-04-03 19:35
Probably there are some libraries to provide that but ,  I would be using the k8s js clients instead of `kubectl` binary. That's probably a nice discussion to have, as we are looking at some refactoring work soon. But, even then, you would still need to implement a timeout mechanism if you  do not want to wait "forever" .

**Comment by bkchr** [comment] 2022-04-03 19:39
I mean we have some general timeout of the CI job of 1 hour or something? Otherwise I would expect that k8 returns an error on spawning a container or it will succeed? I assume it will not take forever to spawn a node?

**Comment by pepoviola** [comment] 2022-04-03 20:25
> What kind of timeout is that? What does it ensures?

Hi @bkchr / @sandreim, This timeouts happens mostly when we need to `scale up` the cluster in `gke`. I have in my backlog change this logic to detect if the wait is because of the `scale up` and backoff the timeout if that the case.

Sorry about the noice, thanks!

**Comment by sandreim** [comment] 2022-08-16 10:49
@pepoviola it seems that things improved recently. Can you confirm the root cause is addressed so we can close this one ?

**Comment by pepoviola** [comment] 2022-08-16 13:02
Hi @sandreim, yes. We fixed on the cluster and code side to improve the performance. We can close this one.
Thanks!

**Comment by sandreim** [comment] 2022-08-16 13:07
Thanks

**Closed by sandreim** 2022-08-16 13:07 UTC
