### ISSUE TITLE
Signal channel is terminated and empty

### ISSUE THREAD

**Issue by crystalin** [paritytech/polkadot#3152] opened 2021-06-01 13:10 UTC
```
2021-05-29 15:23:20 [Relaychain] subsystem exited with error subsystem="availability-recovery-subsystem" err=FromOrigin { origin: "availability-recovery", source: Context("Signal channel is terminated and empty.") }
2021-05-29 15:23:20 [Relaychain] error receiving message from subsystem context for job job="BitfieldSigningJob" err=Context("Signal channel is terminated and empty.")
2021-05-29 15:23:20 [Relaychain] error receiving message from subsystem context for job job="ProvisioningJob" err=Context("Signal channel is terminated and empty.")
2021-05-29 15:23:20 [Relaychain] Shutting down Network Bridge due to error err=Context("Signal channel is terminated and empty.")
2021-05-29 15:23:20 [Relaychain] error receiving message from subsystem context: Context("Signal channel is terminated and empty.") err=Context("Signal channel is terminated and empty.")
2021-05-29 15:23:20 [Relaychain] subsystem exited with error subsystem="network-bridge-subsystem" err=FromOrigin { origin: "network-bridge", source: Context("Received SubsystemError from overseer: Context(\"Signal channel is terminated and empty.\")") }
2021-05-29 15:23:20 [Relaychain] subsystem exited with error subsystem="runtime-api-subsystem" err=Context("Signal channel is terminated and empty.")
2021-05-29 15:23:20 [Relaychain] subsystem exited with error subsystem="statement-distribution-subsystem" err=FromOrigin { origin: "statement-distribution", source: SubsystemReceive(Context("Signal channel is terminated and empty.")) }
2021-05-29 15:23:20 [Relaychain] subsystem exited with error subsystem="collator-protocol-subsystem" err=FromOrigin { origin: "collator-protocol", source: Error(Fatal(SubsystemReceive(Context("Signal channel is terminated and empty.")))) }
2021-05-29 15:23:20 [Relaychain] Essential task `overseer` failed. Shutting down service.
Error: Service(Other("Essential task failed."))
```

This error is observed on multiple parachain nodes (Moonbase Alphanet v8), with diverse hardware/OS. It happens a bit randomly (usually 1 node at a time, and so far we got 5 reports over 100 nodes in a week)
This is using `polkavot-v0.9.2`.
Restarting the node allows it to continue.

**Comment by crystalin** [comment] 2021-06-01 13:10
Another report:
I get the following error pretty consistently, even after starting a fresh node:
```
2021-06-01 10:41:54 [Relaychain] #82171 🗳  Finalized election round with compute ElectionCompute::Unsigned.    
2021-06-01 10:41:54 [Relaychain] [82171] 💸 new validator set of size 6 has been processed for era 23    
2021-06-01 10:41:58 [Relaychain] 💤 Idle (14 peers), best: #82537 (0x34e4…f125), finalized #82432 (0xc4ef…2b7e), ⬇ 3.9kiB/s ⬆ 2.2kiB/s    
2021-06-01 10:41:58 ⚙️  Syncing 19.4 bps, target=#40425 (48 peers), best: #28963 (0xa976…6b7d), finalized #8476 (0x4d43…785a), ⬇ 1.7kiB/s ⬆ 2.4kiB/s    
2021-06-01 10:41:59 [Relaychain] Candidate included without being backed? candidate_hash=0xaea16b3536c74b1ffa7274181487316354434f0485f869cf1642f63d74a807ff
2021-06-01 10:41:59 [Relaychain] Moving approval window from session 6..=11 to 132..=137
2021-06-01 10:42:02 [Relaychain] ✨ Imported #82609 (0xdd79…0640)    
2021-06-01 10:42:02 [Relaychain] ✨ Imported #82610 (0x641f…6df0)    
2021-06-01 10:42:02 [Relaychain] ✨ Imported #82611 (0x441a…f1cc)    
2021-06-01 10:42:02 [Relaychain] ✨ Imported #82612 (0xb3dd…5e76)    
2021-06-01 10:42:02 [Relaychain] ✨ Imported #82613 (0x806f…24da)    
2021-06-01 10:42:02 [Relaychain] ✨ Imported #82613 (0x7540…3df1)    
2021-06-01 10:42:03 [Relaychain] 💤 Idle (15 peers), best: #82613 (0x806f…24da), finalized #82610 (0x641f…6df0), ⬇ 16.3kiB/s ⬆ 6.3kiB/s    
2021-06-01 10:42:03 ⚙️  Syncing 12.9 bps, target=#40436 (48 peers), best: #29028 (0xe572…b366), finalized #8487 (0xb1dc…8bf4), ⬇ 34.5kiB/s ⬆ 3.2kiB/s    
2021-06-01 10:42:06 [Relaychain] ✨ Imported #82614 (0x58a2…34a7)    
2021-06-01 10:42:08 [Relaychain] 💤 Idle (14 peers), best: #82614 (0x58a2…34a7), finalized #82611 (0x441a…f1cc), ⬇ 5.4kiB/s ⬆ 5.7kiB/s    
2021-06-01 10:42:08 ⚙️  Syncing 12.6 bps, target=#40436 (48 peers), best: #29091 (0x79c0…a61e), finalized #8499 (0x5611…c7ff), ⬇ 3.3kiB/s ⬆ 2.8kiB/s    
2021-06-01 10:42:09 [Relaychain] Subsystem statement-distribution-subsystem appears unresponsive.
2021-06-01 10:42:09 [Relaychain] err=Subsystem(Context("Signal channel is terminated and empty."))
2021-06-01 10:42:09 [Relaychain] Essential task `overseer` failed. Shutting down service.    
2021-06-01 10:42:09 [Relaychain] subsystem exited with error subsystem="chain-api-subsystem" err=FromOrigin { origin: "chain-api", source: Context("Signal channel is terminated and empty.") }
Error: Service(Other("Essential task failed."))
```

Specs of the VPS:

```
6 vCPU Cores
16 GB RAM
400 GB SSD
```

**Comment by rphmeier** [comment] 2021-06-14 14:08
duplicate of https://github.com/paritytech/polkadot/issues/3242

**Closed by rphmeier** 2021-06-14 14:08 UTC

**Comment by decentration** [comment] 2021-07-27 15:57
Do you think the specs play a role in this? or more of a firewall issue?
