### ISSUE TITLE
Tokio runtime worker panicked error

### ISSUE THREAD

**Issue by rhacker** [paritytech/polkadot#2435] opened 2021-02-14 19:43 UTC
I try to run a test polkadot instance but got this error:
```
2021-02-15 02:42:16  Parity Polkadot
2021-02-15 02:42:16  ✌️  version 0.8.28-ac5ef00e-x86_64-linux-gnu
2021-02-15 02:42:16  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-02-15 02:42:16  📋 Chain specification: Polkadot
2021-02-15 02:42:16  🏷 Node name: plausible-guide-5334
2021-02-15 02:42:16  👤 Role: FULL
2021-02-15 02:42:16  💾 Database: RocksDb at /home/nxqd/.local/share/polkadot/chains/polkadot/db
2021-02-15 02:42:16  ⛓  Native runtime: polkadot-29 (parity-polkadot-0.tx6.au0)
2021-02-15 02:42:16  👶 Creating empty BABE epoch changes on what appears to be first startup.
2021-02-15 02:42:16  🏷 Local node identity is: 12D3KooWFZYzmzeD3yZakh75hEfXH7yQ8SncRb5scYtkdF1ubAnd
2021-02-15 02:42:16  📦 Highest known block at #0
2021-02-15 02:42:16  〽️ Prometheus server started at 127.0.0.1:9615
2021-02-15 02:42:16  Listening for new connections on 127.0.0.1:9944.

====================

Version: 0.8.28-ac5ef00e-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:581:17
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:484:9
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/sys_common/backtrace.rs:153:18
   4: rust_begin_unwind
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/panicking.rs:483:5
   5: core::panicking::panic_fmt
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/core/src/panicking.rs:85:14
   6: core::option::expect_none_failed
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/core/src/option.rs:1234:5
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <S as futures_core::stream::TryStream>::try_poll_next
   9: <S as futures_core::stream::TryStream>::try_poll_next
  10: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
  11: <S as futures_core::stream::TryStream>::try_poll_next
  12: <S as futures_core::stream::TryStream>::try_poll_next
  13: <S as futures_core::stream::TryStream>::try_poll_next
  14: <S as futures_core::stream::TryStream>::try_poll_next
  15: <futures_util::stream::stream::map::Map<St,F> as futures_core::stream::Stream>::poll_next
  16: <futures_util::stream::try_stream::MapErr<St,F> as futures_core::stream::Stream>::poll_next
  17: libp2p_core::connection::listeners::ListenersStream<TTrans>::poll
  18: libp2p_core::network::Network<TTrans,TInEvent,TOutEvent,THandler>::poll
  19: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
  20: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  21: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  22: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  24: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  25: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  27: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  28: <sc_service::task_manager::WithTelemetrySpan<T> as core::future::future::Future>::poll
  29: std::thread::local::LocalKey<T>::with
  30: futures_executor::local_pool::block_on
  31: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  32: tokio::runtime::task::harness::Harness<T,S>::poll
  33: tokio::runtime::blocking::pool::Inner::run
  34: tokio::runtime::context::enter
  35: std::sys_common::backtrace::__rust_begin_short_backtrace
  36: core::ops::function::FnOnce::call_once{{vtable.shim}}
  37: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/alloc/src/boxed.rs:1042:9
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/alloc/src/boxed.rs:1042:9
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/a1dfd2490a6cb456b92e469fa550dc217e20ad6d/library/std/src/sys/unix/thread.rs:87:17
  38: start_thread
  39: clone


Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /home/nxqd/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix/linux.rs:107

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
```

Environment:  Windows 10 latest WSL 2 environment, I hope this help.

Thanks,

**Comment by bkchr** [comment] 2021-02-14 22:44
Duplicate of: https://github.com/paritytech/substrate/issues/7794

**Closed by bkchr** 2021-02-14 22:44 UTC
