### ISSUE TITLE
Panic while executing block

### ISSUE THREAD

**Issue by BCpowerup** [paritytech/polkadot#579] opened 2019-11-13 01:15 UTC
Version: 0.6.16-e87842ac-x86_64-linux-gnu
Nov 12 17:12:00 joses-HELL polkadot[21523]: stack backtrace:
Nov 12 17:12:00 joses-HELL polkadot[21523]:    0: substrate_panic_handler::set::{{closure}}
Nov 12 17:12:00 joses-HELL polkadot[21523]:    1: std::panicking::rust_panic_with_hook
Nov 12 17:12:00 joses-HELL polkadot[21523]:              at src/libstd/panicking.rs:477
Nov 12 17:12:00 joses-HELL polkadot[21523]:    2: std::panicking::begin_panic
Nov 12 17:12:00 joses-HELL polkadot[21523]:    3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
Nov 12 17:12:00 joses-HELL polkadot[21523]:    4: polkadot_runtime::api::dispatch
Nov 12 17:12:00 joses-HELL polkadot[21523]:    5: std::panicking::try::do_call
Nov 12 17:12:00 joses-HELL polkadot[21523]:    6: __rust_maybe_catch_panic
Nov 12 17:12:00 joses-HELL polkadot[21523]:              at src/libpanic_unwind/lib.rs:80
Nov 12 17:12:00 joses-HELL polkadot[21523]:    7: substrate_executor::native_executor::safe_call
Nov 12 17:12:00 joses-HELL polkadot[21523]:    8: std::thread::local::LocalKey<T>::with
Nov 12 17:12:00 joses-HELL polkadot[21523]:    9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
Nov 12 17:12:00 joses-HELL polkadot[21523]:   10: std::thread::local::LocalKey<T>::with
Nov 12 17:12:00 joses-HELL polkadot[21523]:   11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Nov 12 17:12:00 joses-HELL polkadot[21523]:   12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
Nov 12 17:12:00 joses-HELL polkadot[21523]:   13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Nov 12 17:12:00 joses-HELL polkadot[21523]:   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
Nov 12 17:12:00 joses-HELL polkadot[21523]:   15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 12 17:12:00 joses-HELL polkadot[21523]:   16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 12 17:12:00 joses-HELL polkadot[21523]:   17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 12 17:12:00 joses-HELL polkadot[21523]:   18: substrate_consensus_common::import_queue::import_single_block
Nov 12 17:12:00 joses-HELL polkadot[21523]:   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 12 17:12:00 joses-HELL polkadot[21523]:   20: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Nov 12 17:12:00 joses-HELL polkadot[21523]:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 12 17:12:00 joses-HELL polkadot[21523]:   22: futures_executor::thread_pool::PoolState::work
Nov 12 17:12:00 joses-HELL polkadot[21523]:   23: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 12 17:12:00 joses-HELL polkadot[21523]:   24: std::panicking::try::do_call
Nov 12 17:12:00 joses-HELL polkadot[21523]:   25: __rust_maybe_catch_panic
Nov 12 17:12:00 joses-HELL polkadot[21523]:              at src/libpanic_unwind/lib.rs:80
Nov 12 17:12:00 joses-HELL polkadot[21523]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 12 17:12:00 joses-HELL polkadot[21523]:   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 12 17:12:00 joses-HELL polkadot[21523]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 12 17:12:00 joses-HELL polkadot[21523]:   28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 12 17:12:00 joses-HELL polkadot[21523]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 12 17:12:00 joses-HELL polkadot[21523]:       std::sys_common::thread::start_thread
Nov 12 17:12:00 joses-HELL polkadot[21523]:              at src/libstd/sys_common/thread.rs:13
Nov 12 17:12:00 joses-HELL polkadot[21523]:       std::sys::unix::thread::Thread::new::thread_start
Nov 12 17:12:00 joses-HELL polkadot[21523]:              at src/libstd/sys/unix/thread.rs:79
Nov 12 17:12:00 joses-HELL polkadot[21523]:   29: start_thread
Nov 12 17:12:00 joses-HELL polkadot[21523]:   30: __clone

**Comment by bkchr** [comment] 2019-11-13 01:17
Was there more output? The stack trace does not help.

**Comment by BCpowerup** [comment] 2019-11-13 06:02
that did happen like 5 times in a row...next time will try to copy the stuff better.

**Comment by gavofyork** [comment] 2019-12-04 10:58
Probably a dupe of the other `execute_block`-based panic. Please reopen with more information as and when available.

**Closed by gavofyork** 2019-12-04 10:58 UTC
Labels: F1-panic
