### ISSUE TITLE
v0.9.42 ksm validator finality lags => validator chilled

### ISSUE THREAD

**Issue by SimonKraus** [paritytech/polkadot#7259] opened 2023-05-20 21:24 UTC
Hey crew!

Since updating from v0.9.39-1 to v0.9.42 we experienced multiple lags in finality (finalized block stuck on the same number while best still imports fine).

On the first look it seems related to #7240 but we did neither see low peers, nor does the node stop syncing.

After a few hundred blocks the "finalized" suddenly jumps to the latest (no gradual increase, just a straight jump).

We are alerting if finality is stuck for more than 15 minutes and this alert triggered 16 times in the last 9 days.
While the issue recovers automatically we kept an eye on it but waited.
Now, however, the finality lag was occuring during an epoch-turnover which caused the validator to give up on validation:
`2023-05-19 15:24:54 Backing off claiming new slot for block authorship: finality is lagging.`

The nodes are running on default configuration, only `--state-pruning archive` is added.
Graylog and Prometheus are set up if any context/information is needed.

**Comment by bkchr** [comment] 2023-05-20 22:02
Please run with `-lgrandpa=trace` and report in the following issue: https://github.com/paritytech/substrate/issues/13295

It is very likely a duplicate of this issue. Very unlikely that this is some new kind of issue.

**Closed by bkchr** 2023-05-20 22:02 UTC

**Comment by SimonKraus** [comment] 2023-05-21 05:59
@bkchr with the `-lgrandpa=trace` graylog was registering more than 100k log lines per minute. 

Is that expected behaviour?
For what timespan would you need the logs? 
And do the logs just make sense when finality actually lagging at that very moment?

**Comment by altonen** [comment] 2023-05-21 08:02
I don't think it's expected behavior and the logs could reveal something about this issue. In another log we've received, the node was sending a lot of messages over the GRANDPA substream which could either be absolutely nothing or could somehow interfere with finalization. That's why the logs are useful

**Comment by bkchr** [comment] 2023-05-21 10:03
> And do the logs just make sense when finality actually lagging at that very moment?

That would be the best! But if it is too much probably the first minute would be a good start.

**Comment by andresilva** [comment] 2023-05-23 18:56
@SimonKraus have you tested either v0.9.40 or v0.9.41? Could help with reducing the scope of changes that might have introduced any issue.

**Comment by SimonKraus** [comment] 2023-05-23 19:18
@andresilva due to the known issues in 0.9.40 and 0.9.41 we held back updating and jumped right into 0.9.42
