### ISSUE TITLE
v0.7.20 Kusama CC3 node sync stuck

### ISSUE THREAD

**Issue by uutemai** [paritytech/polkadot#866] opened 2020-02-28 06:43 UTC
Ubuntu Ubuntu 18.04.3 LTS, kernel: Linux version 4.15.0-74-generic

issues # 859 is closed, but I have this problem after running kusama

Kusama CC3 version：v0.7.21 & v0.7.20

![version](https://user-images.githubusercontent.com/32669799/75517275-4d9d1f80-5a39-11ea-9a8b-08f7468dd351.png)

log：
`2020-02-28 06:40:16 Verification failed from peer: UnknownBlock: State already discarded for BlockId::Hash(0xc6051b824a0ae1370dfe4198085c04babbc36d9c8bfcb57a9e3e96a3681bcc10)
2020-02-28 06:40:17 Verification failed from peer: UnknownBlock: State already discarded for BlockId::Hash(0xc6051b824a0ae1370dfe4198085c04babbc36d9c8bfcb57a9e3e96a3681bcc10)
2020-02-28 06:40:17 Verification failed from peer: UnknownBlock: State already discarded for BlockId::Hash(0xc6051b824a0ae1370dfe4198085c04babbc36d9c8bfcb57a9e3e96a3681bcc10)
2020-02-28 06:40:17 Verification failed from peer: UnknownBlock: State already discarded for BlockId::Hash(0xc6051b824a0ae1370dfe4198085c04babbc36d9c8bfcb57a9e3e96a3681bcc10)
2020-02-28 06:40:18 Verification failed from peer: UnknownBlock: State already discarded for BlockId::Hash(0xc6051b824a0ae1370dfe4198085c04babbc36d9c8bfcb57a9e3e96a3681bcc10)`

**Comment by bkchr** [comment] 2020-02-28 08:30
Hey, this is a duplicate of https://github.com/paritytech/polkadot/issues/861

It is already fixed, but we need to release a new version.

**Closed by bkchr** 2020-02-28 08:30 UTC
