### ISSUE TITLE
validator node crashes

### ISSUE THREAD

**Issue by awrelll** [paritytech/polkadot#519] opened 2019-10-30 05:55 UTC
While starting the validator,  I see this error quite often.
```
ExecStart=/opt/bin/polkadot \
         --name DokiaCapital \
         --validator \
         --pruning=archive \
         --chain=kusama \
```
```
ct 30 07:54:21 m2_terra_ion01 polkadot[19895]: ====================
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]: Version: 0.6.5-x86_64-linux-gnu
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]: stack backtrace:
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    0: substrate_panic_handler::panic_hook
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/panic-handler/src/lib.rs:148
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    1: substrate_panic_handler::set::{{closure}}
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/panic-handler/src/lib.rs:58
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    2: std::panicking::rust_panic_with_hook
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at src/libstd/panicking.rs:481
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    3: std::panicking::continue_panic_fmt
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at src/libstd/panicking.rs:384
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    4: rust_begin_unwind
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at src/libstd/panicking.rs:311
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    5: core::panicking::panic_fmt
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at src/libcore/panicking.rs:85
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    6: core::panicking::panic
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at src/libcore/panicking.rs:49
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    7: <u32 as core::ops::arith::Sub>::sub
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/ops/arith.rs:198
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    8: substrate_network::protocol::sync::fork_sync_request
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/network/src/protocol/sync.rs:1290
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:    9: substrate_network::protocol::sync::ChainSync<B>::block_requests::{{closure}}
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at root/.cargo/git/checkouts/substrate-7e08433d4c370a21/93123cc/core/network/src/protocol/sync.rs:583
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:   10: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold::{{closure}}
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/adapters/mod.rs:859
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:   11: core::iter::traits::iterator::Iterator::try_fold
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:              at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/libcore/iter/traits/iterator.rs:1671
Oct 30 07:54:21 m2_terra_ion01 polkadot[19895]:   12: <core::iter::adapters::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::try_fold
Oct 30 07:54:22 m2_terra_ion01 systemd[1]: polkadot.service: Main process exited, code=exited, status=1/FAILURE
Oct 30 07:54:22 m2_terra_ion01 systemd[1]: polkadot.service: Unit entered failed state.
Oct 30 07:54:22 m2_terra_ion01 systemd[1]: polkadot.service: Failed with result 'exit-code'.
```

**Comment by awrelll** [comment] 2019-10-30 06:59
Looks like the error stopped occurring without touching any of the configs. I can't reproduce it.

**Comment by bkchr** [comment] 2019-10-30 07:20
This is a duplicate of your other issue: https://github.com/paritytech/polkadot/issues/518

I close this, as the other one has more information.

**Closed by bkchr** 2019-10-30 07:20 UTC
