### ISSUE TITLE
Parachain validation terminatable (infinite-loop-proof)

### ISSUE THREAD

**Issue by nczhu** [paritytech/polkadot#281] opened 2019-06-03 15:44 UTC
Hey @arkpar, we wanted to put up an issue for this as it’s important for Kusama, please CRUD as needed. Let us know if you need any context around this!

**Comment by arkpar** [comment] 2019-06-03 19:24
The initial implementation will use a separate process for executing validation function. The process can be terminated after a timeout. There will be no metering of any kind.

**Comment by gavofyork** [comment] 2019-07-10 13:25
Duplicate of #147

**Closed by gavofyork** 2019-07-10 13:25 UTC
