### ISSUE TITLE
Inconsistent benchmark machine memory

### ISSUE THREAD

**Issue by LukeWheeldon** [paritytech/polkadot#6486] opened 2022-12-28 16:02 UTC
Running polkadot benchmark machine, I sometimes get a large variance on the memory test:
```
| Memory   | Copy           | 18.50 GiBs  | 14.32 GiBs  | ✅ Pass (129.1 %) |
| Memory   | Copy           | 17.11 GiBs  | 14.32 GiBs  | ✅ Pass (119.4 %) |
| Memory   | Copy           | 3.10 GiBs   | 14.32 GiBs  | ❌ Fail ( 21.6 %) |
| Memory   | Copy           | 3.14 GiBs   | 14.32 GiBs  | ❌ Fail ( 21.9 %) |
| Memory   | Copy           | 22.99 GiBs  | 14.32 GiBs  | ✅ Pass (160.5 %) |
| Memory   | Copy           | 22.39 GiBs  | 14.32 GiBs  | ✅ Pass (156.3 %) |
| Memory   | Copy           | 22.91 GiBs  | 14.32 GiBs  | ✅ Pass (160.0 %) |
| Memory   | Copy           | 22.05 GiBs  | 14.32 GiBs  | ✅ Pass (154.0 %) |
| Memory   | Copy           | 22.96 GiBs  | 14.32 GiBs  | ✅ Pass (160.3 %) |
| Memory   | Copy           | 22.75 GiBs  | 14.32 GiBs  | ✅ Pass (158.8 %) |
```

Hardware specifications:
- Motherboard: X570S AORUS ELITE AX
- CPU: AMD Ryzen 7 5800X 8-Core Processor
- Memory: 4x 16GB DDR4-3200 ECC Unbuffered DIMM CL22 2Rx8 1.2V 8Gbit Micron R (64GB)
- Storage: 2x SSD 980 PRO PCle 4.0 NVMe™ M.2 1TB (Raid0)

Software specifications:
- OS: Debian 11
- Polkadot: 0.9.36-dc25abc712e

The test was ran with the machine freshly started, without any other simultaneous load. Most importantly, the entire memory bank, as well as motherboard, was replaced in order to ensure it wasn't due to some defective hardware.

I have ran this test on several other servers without encountering this issue, so I assume it's possibly some edge case that may not be of high importance at the moment. It will take a while to determine whether this issue is affecting the node in any way. I will make sure to report if it does. Either way I'm only creating this ticket as documentation in case multiple users find themselves affected by this as well.

I would gladly spend time to dig deeper and figure out exactly what is the culprit, I'm however not sure where to begin.

**Comment by bkchr** [comment] 2022-12-31 18:02
CC @ggwpez

**Comment by ggwpez** [comment] 2023-01-02 10:37
Cannot reproduce on my laptop neither, also not with different memory durations. 
Could you try to re-run only the memory benchmark? Maybe the benches influence each other.
```pre
Running with memory-duration 1 secs
| Memory   | Copy           | 20.12 GiBs  | 14.32 GiBs  | ✅ Pass (140.5 %) |
| Memory   | Copy           | 20.76 GiBs  | 14.32 GiBs  | ✅ Pass (144.9 %) |
| Memory   | Copy           | 20.06 GiBs  | 14.32 GiBs  | ✅ Pass (140.1 %) |
| Memory   | Copy           | 20.84 GiBs  | 14.32 GiBs  | ✅ Pass (145.5 %) |
| Memory   | Copy           | 20.93 GiBs  | 14.32 GiBs  | ✅ Pass (146.1 %) |
Running with memory-duration 5 secs
| Memory   | Copy           | 20.74 GiBs  | 14.32 GiBs  | ✅ Pass (144.8 %) |
| Memory   | Copy           | 20.16 GiBs  | 14.32 GiBs  | ✅ Pass (140.7 %) |
| Memory   | Copy           | 20.82 GiBs  | 14.32 GiBs  | ✅ Pass (145.4 %) |
| Memory   | Copy           | 20.88 GiBs  | 14.32 GiBs  | ✅ Pass (145.7 %) |
| Memory   | Copy           | 20.78 GiBs  | 14.32 GiBs  | ✅ Pass (145.1 %) |
Running with memory-duration 10 secs
| Memory   | Copy           | 20.50 GiBs  | 14.32 GiBs  | ✅ Pass (143.1 %) |
| Memory   | Copy           | 20.16 GiBs  | 14.32 GiBs  | ✅ Pass (140.7 %) |
| Memory   | Copy           | 20.37 GiBs  | 14.32 GiBs  | ✅ Pass (142.2 %) |
| Memory   | Copy           | 19.84 GiBs  | 14.32 GiBs  | ✅ Pass (138.5 %) |
| Memory   | Copy           | 20.34 GiBs  | 14.32 GiBs  | ✅ Pass (142.0 %) |
```

Via script:  
```bash
#!/usr/bin/env bash

for D in 1 5 10
do
	echo "Running with memory-duration $D secs"
    for I in {1..5}
    do
        ./target/release/substrate benchmark machine --memory-duration $D --verify-duration 0 --hash-duration 0 --disk-duration 0 --dev --allow-fail 2>&1 | grep "Memory"
    done
done
```

Did you build the binary on the machine that you are testing?  

cc @koute

**Comment by LukeWheeldon** [comment] 2023-01-02 10:56
Likely irrelevant, but it's the first server I am running on an AMD CPU. I have never had this issue before, where all servers were Intel.

I am using the polkadot debian package, so I have edited your script to use the polkadot binary instead of the substrate one, as I assume the tests are identical.

I don't see anything that could be using the RAM at the same time. Particularly not something that would use so much of it so quickly that it would slow down the test itself. Either way there's nothing [0] but Polkadot installed on this server.

As mentioned, I have opened this ticket mainly to inform you of this odd behavior. It probably can be ignored and the ticket closed, but at least it's documented in case someone else find themselves in the same situation. Meanwhile I remain available to run any further testings you would deem useful.

```
$ sh benchmark.sh
Running with memory-duration 1 secs
| Memory   | Copy           | 7.71 GiBs   | 14.32 GiBs  | ❌ Fail ( 53.9 %) |
Running with memory-duration 5 secs
| Memory   | Copy           | 15.92 GiBs  | 14.32 GiBs  | ✅ Pass (111.1 %) |
Running with memory-duration 10 secs
| Memory   | Copy           | 22.43 GiBs  | 14.32 GiBs  | ✅ Pass (156.6 %) |

$ sh benchmark.sh
Running with memory-duration 1 secs
| Memory   | Copy           | 22.54 GiBs  | 14.32 GiBs  | ✅ Pass (157.4 %) |
Running with memory-duration 5 secs
| Memory   | Copy           | 22.77 GiBs  | 14.32 GiBs  | ✅ Pass (158.9 %) |
Running with memory-duration 10 secs
| Memory   | Copy           | 22.30 GiBs  | 14.32 GiBs  | ✅ Pass (155.7 %) |

$ sh benchmark.sh
Running with memory-duration 1 secs
| Memory   | Copy           | 22.71 GiBs  | 14.32 GiBs  | ✅ Pass (158.6 %) |
Running with memory-duration 5 secs
| Memory   | Copy           | 22.77 GiBs  | 14.32 GiBs  | ✅ Pass (159.0 %) |
Running with memory-duration 10 secs
| Memory   | Copy           | 3.80 GiBs   | 14.32 GiBs  | ❌ Fail ( 26.5 %) |

$ sh benchmark.sh
Running with memory-duration 1 secs
| Memory   | Copy           | 22.24 GiBs  | 14.32 GiBs  | ✅ Pass (155.3 %) |
Running with memory-duration 5 secs
| Memory   | Copy           | 6.41 GiBs   | 14.32 GiBs  | ❌ Fail ( 44.7 %) |
Running with memory-duration 10 secs
| Memory   | Copy           | 22.43 GiBs  | 14.32 GiBs  | ✅ Pass (156.6 %) |
```

[0] to be exact, the following packages were installed in addition to polkadot: htop sysstat vnstat git curl tmux nftables neovim rsync gpg linux-cpupower prometheus-node-exporter

**Comment by ggwpez** [comment] 2023-01-04 12:59
>As mentioned, I have opened this ticket mainly to inform you of this odd behavior. It probably can be ignored and the ticket closed, but at least it's documented in case someone else find themselves in the same situation

Okay so then I will close this to clear the backlog.  
One last thing would be to know if this is consistent with other RAM benchmarks. Not sure which ones are good, but you could try that to see if it also reports these oddities.

>I am using the polkadot debian package, so I have edited your script to use the polkadot binary instead of the substrate one, as I assume the tests are identical.

Yea its the same (currently). Using the release binary should also be fine IMO.

**Closed** 2023-01-04 12:59 UTC

**Comment by LukeWheeldon** [comment] 2023-01-04 13:26
I am fairly confident I have found the culprit: overheating. The CPU was regularly throttled, and I can only assume the memory was strongly affected as well, although I am not sure of how. 

After fixing the overheating issue, I have ran the polkadot benchmark test several times and it all came green and normal.

Thank you @ggwpez for taking the time to help out on this.
