### ISSUE TITLE
Validator crashed

### ISSUE THREAD

**Issue by bhkien** [paritytech/polkadot#6410] opened 2022-12-08 07:37 UTC
**Error log:**

```
Dec 08 07:20:20 hp360 polkadot[2306]: ====================
Dec 08 07:20:20 hp360 polkadot[2306]: Version: 0.9.33-c7d6c21242f
Dec 08 07:20:20 hp360 polkadot[2306]:    0: sp_panic_handler::set::{{closure}}
Dec 08 07:20:20 hp360 polkadot[2306]:    1: std::panicking::rust_panic_with_hook
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:702:17
Dec 08 07:20:20 hp360 polkadot[2306]:    2: std::panicking::begin_panic_handler::{{closure}}
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:588:13
Dec 08 07:20:20 hp360 polkadot[2306]:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys_common/backtrace.rs:138:18
Dec 08 07:20:20 hp360 polkadot[2306]:    4: rust_begin_unwind
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/panicking.rs:584:5
Dec 08 07:20:20 hp360 polkadot[2306]:    5: core::panicking::panic_fmt
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/panicking.rs:142:14
Dec 08 07:20:20 hp360 polkadot[2306]:    6: core::result::unwrap_failed
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/core/src/result.rs:1785:5
Dec 08 07:20:20 hp360 polkadot[2306]:    7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
Dec 08 07:20:20 hp360 polkadot[2306]:    8: sp_io::storage::get_version_1
Dec 08 07:20:20 hp360 polkadot[2306]:    9: sp_io::storage::ExtStorageGetVersion1::call
Dec 08 07:20:20 hp360 polkadot[2306]:   10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
Dec 08 07:20:20 hp360 polkadot[2306]:   11: <unknown>
Dec 08 07:20:20 hp360 polkadot[2306]:   12: <unknown>
Dec 08 07:20:20 hp360 polkadot[2306]:   13: <unknown>
Dec 08 07:20:20 hp360 polkadot[2306]:   14: <unknown>
Dec 08 07:20:20 hp360 polkadot[2306]:   15: wasmtime_runtime::traphandlers::catch_traps::call_closure
Dec 08 07:20:20 hp360 polkadot[2306]:   16: wasmtime_setjmp
Dec 08 07:20:20 hp360 polkadot[2306]:   17: sc_executor_wasmtime::runtime::perform_call
Dec 08 07:20:20 hp360 polkadot[2306]:   18: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
Dec 08 07:20:20 hp360 polkadot[2306]:   19: sc_executor_common::wasm_runtime::WasmInstance::call_export
Dec 08 07:20:20 hp360 polkadot[2306]:   20: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
Dec 08 07:20:20 hp360 polkadot[2306]:   21: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
Dec 08 07:20:20 hp360 polkadot[2306]:   22: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
Dec 08 07:20:20 hp360 polkadot[2306]:   23: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
Dec 08 07:20:20 hp360 polkadot[2306]:   24: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Dec 08 07:20:20 hp360 polkadot[2306]:   25: sp_authority_discovery::AuthorityDiscoveryApi::authorities
Dec 08 07:20:20 hp360 polkadot[2306]:   26: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
Dec 08 07:20:20 hp360 polkadot[2306]:   27: sc_authority_discovery::worker::Worker<Client,Network,Block,DhtEventStream>::run::{{closure}}
Dec 08 07:20:20 hp360 polkadot[2306]:   28: tokio::runtime::task::harness::poll_future
Dec 08 07:20:20 hp360 polkadot[2306]:   29: tokio::runtime::task::raw::poll
Dec 08 07:20:20 hp360 polkadot[2306]:   30: tokio::runtime::thread_pool::worker::Context::run_task
Dec 08 07:20:20 hp360 polkadot[2306]:   31: tokio::runtime::thread_pool::worker::run
Dec 08 07:20:20 hp360 polkadot[2306]:   32: tokio::runtime::task::raw::poll
Dec 08 07:20:20 hp360 polkadot[2306]:   33: std::sys_common::backtrace::__rust_begin_short_backtrace
Dec 08 07:20:20 hp360 polkadot[2306]:   34: core::ops::function::FnOnce::call_once{{vtable.shim}}
Dec 08 07:20:20 hp360 polkadot[2306]:   35: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
Dec 08 07:20:20 hp360 polkadot[2306]:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/alloc/src/boxed.rs:1940:9
Dec 08 07:20:20 hp360 polkadot[2306]:       std::sys::unix::thread::Thread::new::thread_start
Dec 08 07:20:20 hp360 polkadot[2306]:              at rustc/897e37553bba8b42751c67658967889d11ecd120/library/std/src/sys/unix/thread.rs:108:17
Dec 08 07:20:20 hp360 polkadot[2306]:   36: <unknown>
Dec 08 07:20:20 hp360 polkadot[2306]:   37: <unknown>
Dec 08 07:20:20 hp360 polkadot[2306]: Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x48a98fd13582c855f0a7831bb689bc0c980d6f5556e0c4bd204c69cde0784f4a"', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/2dff067/primitives/state-machine/src/ext.rs:189
Dec 08 07:20:20 hp360 polkadot[2306]: This is a bug. Please report it at:
Dec 08 07:20:20 hp360 polkadot[2306]:         https://github.com/paritytech/polkadot/issues/new
Dec 08 07:20:20 hp360 systemd[1]: polkadot.service: Main process exited, code=exited, status=1/FAILURE
Dec 08 07:20:20 hp360 systemd[1]: polkadot.service: Failed with result 'exit-code'.
Dec 08 07:20:20 hp360 systemd[1]: polkadot.service: Consumed 22min 14.065s CPU time.
```

**My system:** 
- Ubuntu 22.4.1
- 32 Gb RAM
- Swap: 8192 MB
- Polkadot version: 0.9.33

I am synchronizing db to start a new validator. The sync is approximately at block #15,662,000

**Comment by bkchr** [comment] 2022-12-08 08:10
Duplicate of https://github.com/paritytech/polkadot/issues/6377

**Closed by bkchr** 2022-12-08 08:10 UTC
