### ISSUE TITLE
Chain Reversion Load Test

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#6735] opened 2023-02-16 21:07 UTC
Run concluding invalid disputes (with reversions) on Versi again to see how well we handle those these days. In particular, it would be good to see [this](https://github.com/paritytech/polkadot/pull/6512) in action, ideally with some data how much quicker we can revert under load with that change.

**Comment by BradleyOlson64** [comment] 2023-04-02 20:30
Was able to get confirmation from traces that reversions are primarily happening via overseer message now. Here are some results from Versi with 211 active validators, 5 of which are producing garbage candidates.

Average reversion time after dispute resolution: 
Overseer message - 0.001 Seconds
Chain scraping - 6+ Seconds

97.7% (760/778) of reversions handled via overseer message. Exceptions are when chain selection scrapes a reversion before the dispute coordinator has processed statement imports. This happens when a node is down or isolated from peers while a dispute is being decided.

**Comment by BradleyOlson64** [comment] 2023-04-02 20:32
### Example reversions caused by a single parablock candidate:
**Parent blocks reverted via chainSelectionMessage::RevertBlock:**
2023-04-02 17:09:54.475 TRACE tokio-runtime-worker parachain::dispute-coordinator: Dispute has just concluded against the candidate hash noted. Its parent will be marked as reverted. candidate_hash=0x2d320de018c23484cc73754b03d06a0f7f998fbe6bc29c2c233e739f402d259e parent_block_number=30720 parent_block_hash=0xe0f9f7b42d04f9312827245b990861a10598c2f33fc09e279a5b154fa27ddf18 traceID=60075156079343626186502069228793784847

2023-04-02 17:09:54.475 TRACE tokio-runtime-worker parachain::dispute-coordinator: Dispute has just concluded against the candidate hash noted. Its parent will be marked as reverted. candidate_hash=0x2d320de018c23484cc73754b03d06a0f7f998fbe6bc29c2c233e739f402d259e parent_block_number=30720 parent_block_hash=0xd2af91fcfe4ebfd62d408116ed9f1901e81376f26a70cba02764261a47f0df55 traceID=60075156079343626186502069228793784847

**ChainSelectionMessage::RevertBlocks:**
2023-04-02 17:09:54.476 TRACE tokio-runtime-worker parachain::chain-selection: Block marked as reverted via ChainSelectionMessage::RevertBlocks revert_number=30720 revert_hash=0xe0f9f7b42d04f9312827245b990861a10598c2f33fc09e279a5b154fa27ddf18

2023-04-02 17:09:54.476 TRACE tokio-runtime-worker parachain::chain-selection: Block marked as reverted via ChainSelectionMessage::RevertBlocks revert_number=30720 revert_hash=0xd2af91fcfe4ebfd62d408116ed9f1901e81376f26a70cba02764261a47f0df55

**Block we hadn’t seen is later reverted via On-chain:**
2023-04-02 17:10:36.142 TRACE tokio-runtime-worker parachain::chain-selection: Block marked as reverted via scraped on-chain reversions revert_number=30720 revert_hash=0xa666b128f0d80624754054351135ff76e36f96a5155e58890c3c1b0654c7806e

**Comment by BradleyOlson64** [comment] 2023-04-02 20:35
For each relay parent only one of the two reversion methods can be used, since the first reversion method to trigger removes the relevant block_entry in the chain selection tree.

**Closed** 2023-04-02 20:35 UTC

**Comment by eskimor** [comment] 2023-04-03 07:59
Awesome, thanks Bradley!
