### ISSUE TITLE
Give peers session key with cryptographic proof

### ISSUE THREAD

**Issue by joepetrowski** [paritytech/polkadot#212] opened 2019-04-06 09:55 UTC
```
// Polkadot-specific messages.
#[derive(Debug, Encode, Decode)]
pub enum Message {
	/// As a validator, tell the peer your current session key.
	// TODO: do this with a cryptographic proof of some kind
	SessionKey(SessionKey),
	/// Requesting parachain block data by (relay_parent, candidate_hash).
	RequestBlockData(RequestId, Hash, Hash),
	/// Provide block data by candidate hash or nothing if unknown.
	BlockData(RequestId, Option<BlockData>),
	/// Tell a collator their role.
	CollatorRole(Role),
	/// A collation provided by a peer. Relay parent and collation.
	Collation(Hash, Collation),
}
```

**Comment by rphmeier** [comment] 2019-04-07 10:04
Duplicate of #47

**Closed by rphmeier** 2019-04-07 10:04 UTC
