### ISSUE TITLE
Trie lookup error: Invalid state root

### ISSUE THREAD

**Issue by chrishobcroft** [paritytech/polkadot#424] opened 2019-09-09 11:34 UTC
Running polkadot 0.5.1-60155e89-x86_64-linux-gnu on Kusama

```
2019-09-09 00:20:15 Idle (43 peers), best: #236885 (0x9ea0…e790), finalized #236884 (0x3e18…e5c9), ⬇ 51.3kiB/s ⬆ 64.4kiB/s

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h82cae3535dcc52cb (0x558f8769e1c0)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x558f877dc8a9)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x558f877dc342)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x558f877dc226)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x558f877fe0dd)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h62dbd5a8e5560593 (0x558f869f1e2e)
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_state_machine::Externalities<H>>::storage::hb493a5df659ab9f3 (0x558f866bfaa0)
   7: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index::hb45ea024086571d1 (0x558f8659a39d)
   8: wasmi::func::FuncInstance::invoke::h5b09d54c708b1b31 (0x558f8645abda)
   9: wasmi::runner::Interpreter::start_execution::h4858fcd74c407050 (0x558f867be548)
  10: wasmi::func::FuncInstance::invoke::h5b09d54c708b1b31 (0x558f8645ac6c)
  11: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::h07b2a5c593c7addf (0x558f865c4897)
  12: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::heef7ff72239b90f2 (0x558f8684d75b)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h40e0fef5aad580f3 (0x558f86975ad0)
  14: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h260d5fc78a88d573 (0x558f86993e30)
  15: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hc9d14c9a3c6e6a24 (0x558f8686bdab)
  16: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::hbf93113da3de111a (0x558f864cb9aa)
  17: <polkadot_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::runtime_api::Core<<polkadot_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::Core_initialize_block_runtime_api_impl::hb7bdde40663ba0bc (0x558f86426379)
  18: substrate_client::runtime_api::Core::initialize_block::hb74ada721fa5e557 (0x558f863eb817)
  19: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h646c30bb0a86b123 (0x558f86861708)
  20: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h6f50441f47597513 (0x558f864c856f)
  21: polkadot_primitives::parachain::runtime_decl_for_ParachainHost::validators_call_api_at::hee4b5cbc355a5bcd (0x558f8696430e)
  22: polkadot_primitives::parachain::ParachainHost::validators::h5e101c52657c0562 (0x558f8640701b)
  23: polkadot_validation::ParachainValidation<C,N,P>::get_or_instantiate::he6ddef975679aaa6 (0x558f864f1184)
  24: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::h989eff7555f1e838 (0x558f86aac728)
  25: <futures::future::select::Select<A,B> as futures::future::Future>::poll::h072fc464b56269e6 (0x558f867e7135)
  26: futures::future::chain::Chain<A,B,C>::poll::h31357d6fbbcb8b36 (0x558f86b3a7b9)
  27: futures::task_impl::std::set::h8ed5be9f01d42e6d (0x558f86bcb8f2)
  28: tokio_current_thread::CurrentRunner::set_spawn::h5abebce908ba8889 (0x558f86425bab)
  29: tokio_current_thread::scheduler::Scheduler<U>::tick::h997a8e2f57321237 (0x558f86affef9)
  30: tokio_current_thread::Entered<P>::block_on::hf670e5584a8dc800 (0x558f86425da6)
  31: std::thread::local::LocalKey<T>::with::hc4580ec2b7427ee3 (0x558f868ab364)
  32: std::thread::local::LocalKey<T>::with::hedef1bfa9db36c0b (0x558f868ae83b)
  33: std::thread::local::LocalKey<T>::with::h5f5d9fce2829a137 (0x558f868a0a4b)
  34: std::thread::local::LocalKey<T>::with::h80852b028e491352 (0x558f868a4aa1)
  35: tokio::runtime::current_thread::runtime::Runtime::block_on::h26dab3a938557965 (0x558f8663a955)
  36: std::sys_common::backtrace::__rust_begin_short_backtrace::hbddf5d9de90b8ce0 (0x558f86516db4)
  37: std::panicking::try::do_call::hf4bbd8c887fb36ec (0x558f86a75709)
  38: __rust_maybe_catch_panic (0x558f877e57ca)
             at src/libpanic_unwind/lib.rs:82
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}::h68fd22c3217e11e2 (0x558f8661e134)
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x558f877ca64f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x558f877e4b50)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  42: start_thread (0x7fe6800ec6db)
  43: __clone (0x7fe67fbfd88f)
  44: <unknown> (0x0)

Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x497b17f231f42f7249394bad33a3c7fc39fb35756d6c9db196418327e8bd080c"', src/libcore/result.rs:999

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

```

**Comment by soc1c** [comment] 2019-09-09 11:54
Possibly duplicate of #419

**Comment by bkchr** [comment] 2019-09-26 07:38
Duplicate of https://github.com/paritytech/polkadot/issues/419

**Closed by bkchr** 2019-09-26 07:38 UTC
