### ISSUE TITLE
kusama out of sync data

### ISSUE THREAD

**Issue by kkww8090** [paritytech/polkadot#3746] opened 2021-08-31 08:56 UTC
I'm using the Polkadot binary and its version number is 0.9.9-1-e3901b89c-x86_64-linux-gnu ,Now the Kusama node can't sync data , Bug polkadot node is ok.

![image](https://user-images.githubusercontent.com/18061510/131472933-d2d67b68-927f-4f3a-ad51-a2dec489841f.png)

![image](https://user-images.githubusercontent.com/18061510/131471990-b1f4b5d7-aacd-4df6-8f48-ac565d45b41c.png)

![image](https://user-images.githubusercontent.com/18061510/131473609-4c52bc0c-8ebb-4dc5-b726-5ed6ca3881e2.png)

![image](https://user-images.githubusercontent.com/18061510/131473650-f5245542-91b2-47a4-9ef9-615ce09cc0ba.png)

**Comment by bkchr** [comment] 2021-09-04 19:55
Duplicate of: https://github.com/paritytech/polkadot/issues/3778

**Closed by bkchr** 2021-09-04 19:55 UTC
