### ISSUE TITLE
Failed to allocate memory: "Allocator ran out of space"

### ISSUE THREAD

**Issue by dynasty2016** [paritytech/polkadot#3092] opened 2021-05-24 20:20 UTC
Hello. I am getting the above error message when I try to synchronize the chain data with our node computer. It has been identified as a bug. Has it been reported?

**Comment by Neurone** [comment] 2021-05-24 21:31
It seems the issue #3090

**Comment by pepyakin** [comment] 2021-05-25 13:06
Duplicate of #3090

**Closed by pepyakin** 2021-05-25 13:06 UTC
