### ISSUE TITLE
Dispute coordinator `OrderingProvider` should populate its cache properly in all cases

### ISSUE THREAD

**Issue by eskimor** [paritytech/polkadot#4214] opened 2021-11-03 14:05 UTC
- [ ] On startup, we should fetch `CandidateEvent`s for all currently non finalized blocks, so recovered participations can be prioritized correctly already and all newly in coming ones as well, assuming they concern "old" blocks.
- [ ] On `ActiveLeavesUpdate` we should consider ancestors in a smart way as well, so we will never miss blocks our node is actually aware of.

**Comment by ordian** [comment] 2021-11-03 14:43
(the issue is relevant to #4134 which is not merged into master yet)

**Comment by eskimor** [comment] 2021-11-26 14:25
Looking at data in Rococo, we do see a fraction of participations to be best effort, so we should definitely get this in soon.

**Closed** 2021-12-17 11:07 UTC
Labels: F2-bug, P2-asap
