### ISSUE TITLE
[XCM] Panic in the specific case of `reserveTransferAssets`  when it contains multiple assets

### ISSUE THREAD

**Issue by jiguantong** [paritytech/polkadot#6074] opened 2022-09-29 00:31 UTC
Polkadot related version: v0.9.26
XCM version: 2
Possible related issue: https://github.com/paritytech/cumulus/issues/1700

This seems to be related to [the order of MultiAssets](https://github.com/paritytech/polkadot/blob/c620450de80f76e15a735a0d13efe4540d3053a0/xcm/src/v1/multiasset.rs#L289-L294) as @KiChjang mentioned [here](https://github.com/paritytech/cumulus/issues/1700#issuecomment-1261280719), because it won't panic if I reorder the assets.

This would not only happen on parachains, but also on relay chains

### 1. MultiAssets: 0: {parents: 0, interior: X1(PalletInstance(7)} 1: {parents: 0, interior: X1(PalletInstance(5)}
Encoded call data on [pangolin parachain](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangolin-parachain-rpc.darwinia.network#/extrinsics): `0x0d0201010100a10f0100010100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d01080000010407001ec806000000010405001ed1430001000000`
![image](https://user-images.githubusercontent.com/27564714/192910789-1b7cbf9d-02a6-4531-b2f4-4c2f85cf66e5.png)
The console log of chrome:
```
2022-09-29 08:21:47        RPC-CORE: submitAndWatchExtrinsic(extrinsic: Extrinsic): ExtrinsicStatus:: 1002: Verification Error: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x260bfa - <unknown>!rust_begin_unwind
    1: 0x67dc - <unknown>!core::panicking::panic_fmt::h781687f2782526ba
    2: 0xd1eb0 - <unknown>!TaggedTransactionQueue_validate_transaction
: Runtime error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed
WASM backtrace:

    0: 0x260bfa - <unknown>!rust_begin_unwind
    1: 0x67dc - <unknown>!core::panicking::panic_fmt::h781687f2782526ba
```
And if I test it on my dev node, the node log shows: [pangolin-parachain/src/lib.rs:194:1](https://github.com/darwinia-network/darwinia-parachain/blob/v5.3.2/runtime/pangolin-parachain/src/lib.rs#L194)
```
2022-09-29 08:12:33.560 ERROR tokio-runtime-worker runtime: panicked at 'Bad input data provided to query_info: Codec error', /home/workspace/test/darwinia-parachain/runtime/pangolin-parachain/src/lib.rs:194:1
2022-09-29 08:12:34.379 ERROR tokio-runtime-worker runtime: panicked at 'Bad input data provided to validate_transaction: Codec error', /home/workspace/test/darwinia-parachain/runtime/pangolin-parachain/src/lib.rs:194:1
```
### 2. It won't panic if I swap the order of assets, MultiAssets: 0: {parents: 0, interior: X1(PalletInstance(5)} 1: {parents: 0, interior: X1(PalletInstance(7)}
Encoded call data on [pangolin parachain](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fpangolin-parachain-rpc.darwinia.network#/extrinsics):
`0x0d0201010100a10f0100010100d43593c715fdd31c61141abd04a99fd6822c8558854ccde39a5684e7a56da27d01080000010405001ec806000000010407001ed1430001000000`
![image](https://user-images.githubusercontent.com/27564714/192911747-8cc654ef-ac6e-4973-9eb6-c2e24ab154d8.png)

**Comment by xlc** [comment] 2022-09-29 01:24
This is expected behavior. You are passing an invalid data. As you already discovered, the order of assets must sorted or it will panic.

**Comment by jiguantong** [comment] 2022-09-29 01:33
> This is expected behavior. You are passing an invalid data. As you already discovered, the order of assets must sorted or it will panic.

Really? I don't think it's UX friendly

**Comment by KiChjang** [comment] 2022-09-29 02:52
I've posted this issue on polkadot.js before: https://github.com/polkadot-js/api/issues/4537.

On the chain side, we have to get the MultiAssets sorted, because we specifically want them to not contain duplicate entries, otherwise the validation algorithm would be an O(NlogN) operation instead of it being O(N).

In other words, this is really a UI/UX issue, and we won't fix it on the chain side.

**Comment by jiguantong** [comment] 2022-09-29 02:55
Ok, I see.

**Closed** 2022-09-29 02:56 UTC
