### ISSUE TITLE
just got this, dono what it relates to.

### ISSUE THREAD

**Issue by BCpowerup** [paritytech/polkadot#512] opened 2019-10-28 20:03 UTC
14: wasmi::runner::Interpreter::start_execution
  15: wasmi::func::FuncInstance::invoke
  16: std::thread::local::LocalKey<T>::with
  17: substrate_executor::wasmi_execution::call_in_wasm_module
  18: <substrate_executor::wasmi_execution::WasmiRuntime as substrate_executor::wasm_runtime::WasmRuntime>::call
  19: std::thread::local::LocalKey<T>::with
  20: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
  21: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
  22: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
  23: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  24: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at
  25: substrate_client::runtime_api::Core::initialize_block
  26: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
  27: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  28: substrate_client::block_builder::api::BlockBuilder::check_inherents
  29: <substrate_consensus_babe::BabeVerifier<B,E,Block,RA,PRA> as substrate_consensus_common::import_queue::Verifier<Block>>::verify
  30: substrate_consensus_common::import_queue::import_single_block
  31: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  32: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  33: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  34: futures_executor::thread_pool::PoolState::work
  35: std::sys_common::backtrace::__rust_begin_short_backtrace
  36: std::panicking::try::do_call
  37: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  38: core::ops::function::FnOnce::call_once{{vtable.shim}}
  39: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  41: start_thread
  42: __clone

Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0xc70362c5a413a1e87bdad80aa8dbee037cf7adab237981ff238ddacc1686021d"', src/libcore/result.rs:1084

**Comment by bkchr** [comment] 2019-10-29 13:05
Duplicate of: https://github.com/paritytech/polkadot/issues/419

**Closed by bkchr** 2019-10-29 13:05 UTC
