### ISSUE TITLE
Kusama Node Crashed

### ISSUE THREAD

**Issue by Ch1p999** [paritytech/polkadot#438] opened 2019-09-17 11:25 UTC
===================
stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
   6: substrate_executor::wasm_runtimes_cache::RuntimesCache::fetch_runtime
   7: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::runtime_version
   8: substrate_client::runtime_api::ApiExt::has_api
   9: substrate_consensus_babe::epoch_from_runtime
  10: <substrate_consensus_babe::BabeVerifier<B,E,Block,RA,PRA,T> as substrate_consensus_common::import_queue::Verifier<Block>>::verify
  11: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  12: futures_util::future::chain::Chain<Fut1,Fut2,Data>::poll
  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  14: futures_executor::thread_pool::PoolState::work
  15: std::sys_common::backtrace::__rust_begin_short_backtrace
  16: std::panicking::try::do_call
  17: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  18: core::ops::function::FnOnce::call_once{{vtable.shim}}
  19: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  20: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  21: start_thread
  22: __clone
Thread 'import-queue-worker-0' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x085e1968fff74bcc139be8e5f357a1e74f3f0defa6e990543e3c85caacd88f83"', src/libcore/result.rs:999

**Comment by bkchr** [comment] 2019-09-26 07:38
Duplicate of https://github.com/paritytech/polkadot/issues/419

**Closed by bkchr** 2019-09-26 07:38 UTC
