### ISSUE TITLE
Trie: Extension Node Removal

### ISSUE THREAD

**Issue by nczhu** [paritytech/polkadot#279] opened 2019-06-03 15:07 UTC
_Wanted to put up an issue for this as it’s important for Kusama, please CRUD as needed._

Polkadot RE spec include changes to substrate patricia trie. Some slight codec changes and the removal of trie extension node.

Related issue for additional context: https://github.com/paritytech/trie/pull/11

Currently owned by @cheme

**Comment by gavofyork** [comment] 2019-07-10 13:29
Duplicate of https://github.com/paritytech/substrate/pull/2815

**Comment by rphmeier** [comment] 2022-10-26 22:22
outdated/more of a cumulus concern

**Closed by rphmeier** 2022-10-26 22:22 UTC
