### ISSUE TITLE
Support query historic parachain block PoV size

### ISSUE THREAD

**Issue by boundless-forest** [paritytech/polkadot#7216] opened 2023-05-12 03:48 UTC
The original question here: [Is there a way to find the historic parachain block PoV size?](https://substrate.stackexchange.com/questions/8436/is-there-a-way-to-find-the-historic-parachain-block-pov-size)

As far as I know, once the block is included in the Relay Chain and finalized, the PoV is no longer necessary and is not stored indefinitely by the validators. If I have missed something, please correct me. 

I only know that the PoV size is currently printed on the callator console, but seems no way to query the historical block PoV size. 

```sh
2022-03-21 14:48:06 [Parachain] PoV size { header: 0.181640625kb, extrinsics: 3.525390625kb, storage_proof: 4.6123046875kb }
2022-03-21 14:48:06 [Parachain] Compressed PoV size: 7.3828125kb
2022-03-21 14:48:06 [Parachain] Produced proof-of-validity candidate. block_hash=0x4f1e697ca979e8f00015ba04f544cb87a31aaf22867a4dd0c36c4a2a69349e09
```

After digging into the code, I find it might be possible to address this by expanding the existing event `CandidateIncluded` `CandidateReceipt` with `pov_size`, there is already has a field `pov_hash`.

![image](https://github.com/paritytech/polkadot/assets/11801722/09df6b9a-a312-48b0-9b2e-feb9c314fbc0)

- https://github.com/paritytech/polkadot/blob/df61c0bf0834f650e79ddd1a74dea34081ff2b46/primitives/src/v4/mod.rs#L1007
- https://github.com/paritytech/polkadot/blob/dbae30efe080a1d41fe54ef4da8af47614c9ca93/node/collation-generation/src/lib.rs#L361

**Comment by sandreim** [comment] 2023-05-12 10:27
May I ask what is the usecase for this ? IMO the relay chain should only keep data relevant to consensus and PoV size is not needed.

**Comment by sandreim** [comment] 2023-05-12 10:28
CC @ordian for some tooling that might help solve this.

**Comment by ordian** [comment] 2023-05-12 11:26
Yes, I have an idea of collaboration with the Data Team at Parity. Hopefully, we'll implement it this month.

**Comment by bkchr** [comment] 2023-05-12 20:29
This is a duplicate of https://github.com/paritytech/cumulus/issues/1423

**Closed by bkchr** 2023-05-12 20:29 UTC
