### ISSUE TITLE
Impossible to launch node

### ISSUE THREAD

**Issue by msuiche** [paritytech/polkadot#2355] opened 2021-01-31 14:43 UTC
I was trying to run polkadot locally but I got the following error:

```
msuiche@---:/mnt/d/Polkadot$ ./polkadot --name "OKLM Rocket 🚀"
2021-01-31 18:42:09  Parity Polkadot
2021-01-31 18:42:09  ✌️  version 0.8.27-2f845699-x86_64-linux-gnu
2021-01-31 18:42:09  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-01-31 18:42:09  📋 Chain specification: Polkadot
2021-01-31 18:42:09  🏷 Node name: OKLM Rocket 🚀
2021-01-31 18:42:09  👤 Role: FULL
2021-01-31 18:42:09  💾 Database: RocksDb at /home/msuiche/.local/share/polkadot/chains/polkadot/db
2021-01-31 18:42:09  ⛓  Native runtime: polkadot-27 (parity-polkadot-0.tx5.au0)
2021-01-31 18:42:09  👶 Creating empty BABE epoch changes on what appears to be first startup.
2021-01-31 18:42:09  🏷 Local node identity is: ---------------------------------------
2021-01-31 18:42:09  📦 Highest known block at #0
2021-01-31 18:42:09  〽️ Prometheus server started at 127.0.0.1:9615
2021-01-31 18:42:09  Listening for new connections on 127.0.0.1:9944.

====================

Version: 0.8.27-2f845699-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:581
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:484
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys_common/backtrace.rs:153
   4: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   5: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   6: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   9: <sc_network::behaviour::Behaviour<B,H> as libp2p_swarm::behaviour::NetworkBehaviour>::poll
  10: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
  11: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  12: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  13: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  16: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  18: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  19: std::thread::local::LocalKey<T>::with
  20: futures_executor::local_pool::block_on
  21: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  22: tokio::runtime::task::harness::Harness<T,S>::poll
  23: tokio::runtime::blocking::pool::Inner::run
  24: tokio::runtime::context::enter
  25: std::sys_common::backtrace::__rust_begin_short_backtrace
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/alloc/src/boxed.rs:1042
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/sys/unix/thread.rs:87
  28: start_thread
  29: clone


Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix/linux.rs:107

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new
```

**Comment by bkchr** [comment] 2021-01-31 23:17
Duplicate of https://github.com/paritytech/substrate/issues/7794

**Closed by bkchr** 2021-01-31 23:17 UTC
