### ISSUE TITLE
Switching IP networks causes warnings

### ISSUE THREAD

**Issue by DemiMarie-parity** [paritytech/polkadot#1084] opened 2020-05-10 22:46 UTC
When I switch from one IP network to another, I get lots of warnings of the form “💔 Called on_block_announce with a bad peer ID”.

**Comment by bkchr** [comment] 2020-05-11 08:42
CC @tomaka

**Comment by tomaka** [comment] 2020-05-11 08:48
Closing as duplicate of https://github.com/paritytech/substrate/issues/5592

**Closed by tomaka** 2020-05-11 08:48 UTC
