### ISSUE TITLE
v0.8.19 random crash for Kusama Network

### ISSUE THREAD

**Issue by jasl** [paritytech/polkadot#1538] opened 2020-08-05 08:11 UTC
- Ubuntu 18.04 latest, 2 Core 8G memory
- 0.8.19
- Linux binary from GitHub releases page
- Kusama chain
- Validator role (connect to 2 sentry nodes)

Start command:

```bash
#!/bin/bash

WORK_PATH=$(dirname $(readlink -f "$0"))
NODE_NAME="kusama-validator-2"
CHAIN_NAME="kusama"
RESERVED_NODES="/ip4/10.156.0.2/tcp/30333/p2p/12D3KooWKcptZZD15bMSjck8qwj9wo56iMsM45nyd2Hk2bMdhwnD /ip4/10.148.0.2/tcp/30333/p2p/12D3KooWDwEF58cKyxrHCC8zFf5aBu6pys8aZHR1DkmuNAUc1Xb2"
WASM_EXECUTION_MODE="Compiled" # Interpreted

$WORK_PATH/polkadot \
  --chain $CHAIN_NAME \
  --base-path $WORK_PATH \
  --database paritydb \
  --wasm-execution $WASM_EXECUTION_MODE \
  --name $NODE_NAME \
  --reserved-only \
  --reserved-nodes $RESERVED_NODES \
  --validator \
  "$@"
```

Our nodes had slashed twice recently, so I discovered logs to figured out, then I found this

```
2020-08-05 07:43:38 🔍 Discovered new external address for our node: /ip4/10.0.1.215/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:38 🙇 You are using the peer ID QmWThvuDonoYRxpUfJpm7t7HKb56pQJy9YQUemwexUWEzq. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmPVbzttk7DbyMcAoo95PxNtsGAVq98uLivGZhTaB7Yy7M. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmVVYhJJx59nfEvqzAFankyCAxkkXJUajpuH449gHzvdN5. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmVVYhJJx59nfEvqzAFankyCAxkkXJUajpuH449gHzvdN5. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmPVbzttk7DbyMcAoo95PxNtsGAVq98uLivGZhTaB7Yy7M. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmVVYhJJx59nfEvqzAFankyCAxkkXJUajpuH449gHzvdN5. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmVVYhJJx59nfEvqzAFankyCAxkkXJUajpuH449gHzvdN5. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmVVYhJJx59nfEvqzAFankyCAxkkXJUajpuH449gHzvdN5. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmQZEm9395wgF3ztkfqwNgx3yrqsLEECYB3cd7mZDavyxX. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:38 🙇 You are using the peer ID QmQZEm9395wgF3ztkfqwNgx3yrqsLEECYB3cd7mZDavyxX. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:39 🔍 Discovered new external address for our node: /ip4/10.156.1.57/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:39 🙇 You are using the peer ID QmQZEm9395wgF3ztkfqwNgx3yrqsLEECYB3cd7mZDavyxX. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
2020-08-05 07:43:39 🔍 Discovered new external address for our node: /ip4/10.156.3.194/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:40 🔍 Discovered new external address for our node: /ip4/10.36.2.1/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:41 🔍 Discovered new external address for our node: /ip4/10.156.1.57/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:41 🔍 Discovered new external address for our node: /ip4/10.156.1.43/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:41 💤 Idle (2 peers), best: #3473580 (0x833a…a6a9), finalized #3473577 (0x6912…4a05), ⬇ 546.8kiB/s ⬆ 383.8kiB/s
2020-08-05 07:43:42 🔍 Discovered new external address for our node: /ip4/10.131.135.228/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:43 🔍 Discovered new external address for our node: /ip4/10.156.1.53/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:44 ✨ Imported #3473581 (0x0539…2b15)
2020-08-05 07:43:45 🔍 Discovered new external address for our node: /ip4/10.0.0.2/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
2020-08-05 07:43:46 🔍 Discovered new external address for our node: /ip4/10.0.0.5/tcp/30333/p2p/12D3KooWKPmEpVNvf7e3cr4kpHSStchk7DvC42c8gE2nUZ9zAxjF
====================
Version: 0.8.19-3a189f5d-x86_64-linux-gnu
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: <unknown>
Thread 'tokio-runtime-worker' panicked at 'Our process exists. qed.: Io(Custom { kind: Other, error: IoErrorWrapper { path: "/proc/1664577/stat", inner: None } }, Some("/proc/1664577/stat"))', /usr/local/cargo/git/checkouts/substrate-7e08433d4c370a21/065b0f3/client/service/src/metrics.rs:210
This is a bug. Please report it at:
        https://github.com/paritytech/polkadot/issues/new
```

The validator node crash randomly, but we have auto restart, it look good until crash again, because log too large so I'm not stats how often the crash will occaur.

Another question, I saw many output like this

```
2020-08-05 07:43:38 🙇 You are using the peer ID QmWThvuDonoYRxpUfJpm7t7HKb56pQJy9YQUemwexUWEzq. This peer ID uses a legacy, deprecated representation that will no longer be supported in the future. Please refresh it by performing a RPC query to the appropriate node, by looking at its logs, or by using `subkey inspect-node-key` on its private key.
```

These peer ids are not our validator and sentry nodes', why I got this warning?

**Comment by bkchr** [comment] 2020-08-05 08:59
Duplicate of: https://github.com/paritytech/polkadot/issues/1507

**Closed by bkchr** 2020-08-05 08:59 UTC
