### ISSUE TITLE
tokio-runtime-worker panic

### ISSUE THREAD

**Issue by SidepocketNeo** [paritytech/polkadot#2314] opened 2021-01-24 08:26 UTC
Was running in Ubuntu and Kali subsystems after install. Here is the error in full:

2021-01-24 03:24:14  Parity Polkadot
2021-01-24 03:24:14  ✌️  version 0.8.27-2f845699-x86_64-linux-gnu
2021-01-24 03:24:14  ❤️  by Parity Technologies <admin@parity.io>, 2017-2021
2021-01-24 03:24:14  📋 Chain specification: Westend
2021-01-24 03:24:14  🏷 Node name: second-hand-love-0440
2021-01-24 03:24:14  👤 Role: FULL
2021-01-24 03:24:14  💾 Database: RocksDb at /root/.local/share/polkadot/chains/westend2/db
2021-01-24 03:24:14  ⛓  Native runtime: westend-47 (parity-westend-0.tx3.au2)
2021-01-24 03:24:15  🔨 Initializing Genesis block/state (state: 0x7e92…746f, header-hash: 0xe143…423e)
2021-01-24 03:24:15  👴 Loading GRANDPA authority set from genesis on what appears to be first startup.
2021-01-24 03:24:15  ⏱  Loaded block-time = 6000 milliseconds from genesis on first-launch
2021-01-24 03:24:15  👶 Creating empty BABE epoch changes on what appears to be first startup.
2021-01-24 03:24:15  🏷 Local node identity is: 12D3KooWGJ1BuPC54fqtv8VgsLgnQC6ibVEE8uJT1XBKaBumg6ci
2021-01-24 03:24:15  📦 Highest known block at #0
2021-01-24 03:24:15  〽️ Prometheus server started at 127.0.0.1:9615
2021-01-24 03:24:15  Listening for new connections on 127.0.0.1:9944.

====================

Version: 0.8.27-2f845699-x86_64-linux-gnu

   0: sp_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:597
   2: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:499
   3: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys_common/backtrace.rs:141
   4: rust_begin_unwind
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/panicking.rs:495
   5: core::panicking::panic_fmt
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/panicking.rs:92
   6: core::option::expect_none_failed
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/core/src/option.rs:1268
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <sc_network::discovery::DiscoveryBehaviour as libp2p_swarm::behaviour::NetworkBehaviour>::poll
   9: libp2p_swarm::ExpandedSwarm<TBehaviour,TInEvent,TOutEvent,THandler>::poll_next_event
  10: <sc_network::service::NetworkWorker<B,H> as core::future::future::Future>::poll
  11: sc_service::build_network_future::{{closure}}::{{closure}}::{{closure}}
  12: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  13: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  14: <sc_service::task_manager::prometheus_future::PrometheusFuture<T> as core::future::future::Future>::poll
  15: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
  16: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
  17: std::thread::local::LocalKey<T>::with
  18: futures_executor::local_pool::block_on
  19: tokio::runtime::task::core::Core<T,S>::poll
  20: <std::panic::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
  21: tokio::runtime::task::harness::Harness<T,S>::poll
  22: tokio::runtime::blocking::pool::Inner::run
  23: tokio::runtime::context::enter
  24: std::sys_common::backtrace::__rust_begin_short_backtrace
  25: core::ops::function::FnOnce::call_once{{vtable.shim}}
  26: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/alloc/src/boxed.rs:1307
      std::sys::unix::thread::Thread::new::thread_start
             at /rustc/e1884a8e3c3e813aada8254edfa120e85bf5ffca/library/std/src/sys/unix/thread.rs:71
  27: start_thread
  28: clone

Thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 22, kind: InvalidInput, message: "Invalid argument" }', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/if-watch-0.1.7/src/unix/linux.rs:107

**Comment by bkchr** [comment] 2021-01-24 12:36
Duplicate of: https://github.com/paritytech/substrate/issues/7794

**Closed** 2021-01-24 12:37 UTC
