### ISSUE TITLE
Trie lookup error: Invalid state root: ... src/libcore/result.rs:1051

### ISSUE THREAD

**Issue by jacksteroo** [paritytech/polkadot#432] opened 2019-09-12 07:46 UTC
There was a reorg prior to the process panicking.  This is Kusama / 0.5.1

```
2019-09-12 06:19:17 Idle (47 peers), best: #283381 (0xb0e4…f304), finalized #283381 (0xb0e4…f304), ⬇ 81.9kiB/s ⬆ 79.4kiB/s
2019-09-12 06:19:18 Starting parachain attestation session on top of parent 0x32fac33bae8c461cd2356dc4a4186032f4e559444ed301b90a5de17e8b99a1a1. Local parachain duty is None
2019-09-12 06:19:18 Imported #283382 (0x32fa…a1a1)
2019-09-12 06:19:22 Idle (46 peers), best: #283382 (0x32fa…a1a1), finalized #283382 (0x32fa…a1a1), ⬇ 66.0kiB/s ⬆ 102.6kiB/s
2019-09-12 06:19:25 Imported #283383 (0x3b54…2233)
2019-09-12 06:19:25 Starting parachain attestation session on top of parent 0x3b54ad094f1b95a13429a7b23bf2895e4d1fb31177f7dcc57ff469bcc8042233. Local parachain duty is None
2019-09-12 06:19:26 Reorg from #283383,0x3b54…2233 to #283383,0x2e23…af00, common ancestor #283382,0x32fa…a1a1
2019-09-12 06:19:26 Imported #283383 (0x2e23…af00)
2019-09-12 06:19:26 Starting parachain attestation session on top of parent 0x2e23dd5fe0984ae2b8b865f7a9ce3af04205a6b31392ea33b077e41d809eaf00. Local parachain duty is None
2019-09-12 06:19:27 Idle (47 peers), best: #283383 (0x2e23…af00), finalized #283382 (0x32fa…a1a1), ⬇ 46.2kiB/s ⬆ 69.4kiB/s
2019-09-12 06:19:30 Imported #283384 (0xe276…efee)

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_state_machine::Externalities<H>>::storage
   7: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index
   8: wasmi::func::FuncInstance::invoke
   9: wasmi::runner::Interpreter::start_execution
  10: wasmi::func::FuncInstance::invoke
  11: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module
  12: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux
  14: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler
  15: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
  16: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  17: <polkadot_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::runtime_api::Core<<polkadot_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::Core_initialize_block_runtime_api_impl
  18: substrate_client::runtime_api::Core::initialize_block
  19: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call
  20: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at
  21: polkadot_primitives::parachain::runtime_decl_for_ParachainHost::validators_call_api_at
  22: polkadot_primitives::parachain::ParachainHost::validators
  23: polkadot_validation::ParachainValidation<C,N,P>::get_or_instantiate
  24: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll
  25: <futures::future::select::Select<A,B> as futures::future::Future>::poll
  26: futures::future::chain::Chain<A,B,C>::poll
  27: futures::task_impl::std::set
  28: tokio_current_thread::CurrentRunner::set_spawn
  29: tokio_current_thread::scheduler::Scheduler<U>::tick
  30: tokio_current_thread::Entered<P>::block_on
  31: std::thread::local::LocalKey<T>::with
  32: std::thread::local::LocalKey<T>::with
  33: std::thread::local::LocalKey<T>::with
  34: std::thread::local::LocalKey<T>::with
  35: tokio::runtime::current_thread::runtime::Runtime::block_on
  36: std::sys_common::backtrace::__rust_begin_short_backtrace
  37: std::panicking::try::do_call
  38: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:82
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/liballoc/boxed.rs:766
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at /rustc/69656fa4cbafc378fd63f9186d93b0df3cdd9320/src/liballoc/boxed.rs:766
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  42: start_thread
  43: __clone


Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x87bcf0c756a35e2c6163af00c8043769fae2fb9a6ebb165883871e8247456267"', src/libcore/result.rs:1051
```

**Comment by bkchr** [comment] 2019-09-26 07:37
Duplicate of: https://github.com/paritytech/polkadot/issues/419

**Closed by bkchr** 2019-09-26 07:37 UTC
