### ISSUE TITLE
Polkadot  testnet stop geerate new blockes. 

### ISSUE THREAD

**Issue by lansehuiyi6** [paritytech/polkadot#7351] opened 2023-06-12 03:29 UTC
https://telemetry.polkadot.io/#list/

Polkadot  testnet stop geerate new blockes. #16,164,348

**Comment by bkchr** [comment] 2023-06-12 10:49
Duplicate of: https://github.com/paritytech/polkadot/issues/7352

**Closed by bkchr** 2023-06-12 10:49 UTC
