### ISSUE TITLE
Validator node crash

### ISSUE THREAD

**Issue by ZhongweiZhang** [paritytech/polkadot#30] opened 2018-09-27 08:00 UTC
I deployed a Local Two-node Testnet with 2 validators and a adder-collater. The first Alice validator crashed not long after the collater joined. logs are attached.
[polkadot_test.txt](https://github.com/paritytech/polkadot/files/2423050/polkadot_test.txt)

**Comment by arkpar** [comment] 2018-09-27 10:43
@tomaka

**Comment by tomaka** [comment] 2018-09-27 11:35
Yes this has been fixed in substrate.

**Comment by tomaka** [comment] 2018-09-27 11:36
Closing as duplicate of #18

**Closed by tomaka** 2018-09-27 11:36 UTC
