### ISSUE TITLE
Kusama Validator stuck at block 16761589, chilled

### ISSUE THREAD

**Issue by nicolasochem** [paritytech/polkadot#6771] opened 2023-02-23 17:14 UTC
Polkadot v0.9.38, running in a vm with 4 vCPUs and 16Gi RAM.

Nothing special in the logs, it just stopped importing blocks:

```
2023-02-23 04:59:48 | 2023-02-23 12:59:48 💤 Idle (20 peers), best: #16761587 (0xc2a0…ee14), finalized #16761536 (0x0ac0…3dfb), ⬇ 565.9kiB/s ⬆ 1.2MiB/s |  
-- | -- | --
  |   | 2023-02-23 04:59:53 | 2023-02-23 12:59:53 💤 Idle (20 peers), best: #16761587 (0xc2a0…ee14), finalized #16761536 (0x0ac0…3dfb), ⬇ 246.1kiB/s ⬆ 605.2kiB/s |  
  |   | 2023-02-23 04:59:56 | 2023-02-23 12:59:56 ✨ Imported #16761588 (0x2fe1…f6af) |  
  |   | 2023-02-23 04:59:56 | 2023-02-23 12:59:56 ✨ Imported #16761589 (0xf526…5554) |  
  |   | 2023-02-23 04:59:58 | 2023-02-23 12:59:58 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 1022.4kiB/s ⬆ 752.6kiB/s |  
  |   | 2023-02-23 05:00:03 | 2023-02-23 13:00:03 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 183.0kiB/s ⬆ 1.2MiB/s |  
  |   | 2023-02-23 05:00:08 | 2023-02-23 13:00:08 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 217.6kiB/s ⬆ 555.3kiB/s |  
  |   | 2023-02-23 05:00:13 | 2023-02-23 13:00:13 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 281.4kiB/s ⬆ 711.4kiB/s
```

Then over one hour later it started again without intervention. In between, it was continuously reporting having 20 peers.

```


2023-02-23 06:09:59 | 2023-02-23 14:09:59 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 517.7kiB/s ⬆ 554.0kiB/s |  
-- | -- | --
  |   | 2023-02-23 06:10:04 | 2023-02-23 14:10:04 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 435.4kiB/s ⬆ 435.8kiB/s |  
  |   | 2023-02-23 06:10:09 | 2023-02-23 14:10:09 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 454.9kiB/s ⬆ 420.5kiB/s |  
  |   | 2023-02-23 06:10:14 | 2023-02-23 14:10:14 💤 Idle (20 peers), best: #16761589 (0xf526…5554), finalized #16761536 (0x0ac0…3dfb), ⬇ 519.0kiB/s ⬆ 459.2kiB/s |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:17 | 2023-02-23 14:10:17 Accepting new connection 1/100 |  
  |   | 2023-02-23 06:10:18 | 2023-02-23 14:10:18 ✨ Imported #16761590 (0x22a8…0efe) |  
  |   | 2023-02-23 06:10:18 | 2023-02-23 14:10:18 Candidate included without being backed? candidate_hash=0xc9933b2018526a713714e4928c3d4a390dab4165b81beeac8e2da94d446365a5 traceID=267939293995967800832292012200958970425 |  
  |   | 2023-02-23 06:10:18 | 2023-02-23 14:10:18 Candidate included without being backed? candidate_hash=0x9ab9253b9cebcd7b77a7979485d609cc81d548c39cf033e53902a2444048b54e traceID=205662441441887640454305837767915342284 |  
  |   | 2023-02-23 06:10:18 | 2023-02-23 14:10:18 Candidate included without being backed? candidate_hash=0x26f0054905d4df3acb893b9a96666ad9cdd919ee05020fc5f29143616ed45f8a traceID=51756922283383815096008933605972011737

```

This setup was working succesfully for a long time and never got chilled, the only recent change is the upgrade to v0.9.38. Another validator

**Comment by bkchr** [comment] 2023-02-23 21:35
Duplicate of https://github.com/paritytech/polkadot/issues/6696

**Comment by nicolasochem** [comment] 2023-03-14 23:45
@bkchr  please reopen

**Comment by bkchr** [comment] 2023-03-15 05:44
@nicolasochem this is a duplicate of the issue I mentioned above. You can comment there!

**Comment by nicolasochem** [comment] 2023-03-23 23:06
I'm getting this a lot more with 0.9.40.

**Comment by altonen** [comment] 2023-03-24 14:27
@nicolasochem can you run the node with `-lsync,sub-libp2p=trace`?

**Comment by nicolasochem** [comment] 2023-03-27 04:26
Sorry, this yields over one thousand lines a second... I'm not able to process these kind of logs in my environment. Is there any less verbose setting?

**Comment by altonen** [comment] 2023-03-27 07:16
I don't think it should print a thousand lines a second though so something is wrong. Can you confirm that your issues are not caused by NAT configurations as outlined [here](https://github.com/paritytech/polkadot/issues/6696#issuecomment-1482459441)?

**Comment by nicolasochem** [comment] 2023-03-27 14:58
I am using a network load-balancer for ingress p2p traffic and passing the ip to the validator with `--public-addr`.

With this mechanism, each validator has its own IP but I have several validators in the same virtual machine behind a NAT so outbound connections may look like they come from the same IP. But it should not matter. The nodes have plenty of established connections to other peers, yet they stop syncing. It never mattered before.

**Comment by nicolasochem** [comment] 2023-03-27 15:12
Here are samples when it's working properly: 

https://gist.github.com/nicolasochem/c2fed7c268fa5342d2c472d487e3e3c0

I'll post more if it gets into the unsynced state.

**Comment by nicolasochem** [comment] 2023-03-27 15:26
Yes, I never had this issue with 0.9.37, it happened once in 0.9.38, once in 0.9.39 and now it's happening very frequently in 0.9.40 so I would definitely look at changes between 0.9.39 and 0.9.40. Besides, plenty of validators are reporting sync issues on matrix chat. I am not sure if all of them have a similar setup as mine.

**Comment by altonen** [comment] 2023-05-16 16:31
There hasn't been any update so I assume the node is working now. If it's not, please reopen the issue

**Closed by altonen** 2023-05-16 16:31 UTC
Labels: I3-bug

**Comment by nicolasochem** [comment] 2023-05-16 16:38
Yes, no more issues as of 0.9.42.
