### ISSUE TITLE
0.9.41 archive node panic (paritydb)

### ISSUE THREAD

**Issue by ScepticMatt** [paritytech/polkadot#7056] opened 2023-04-11 14:39 UTC
new archive node panicked at block #11954688

error log 
```
Apr 09 02:03:28: 2023-04-09 02:03:28 ⚙️  Syncing 63.8 bps, target=#17399345 (40 peers), best: #11955089 (0x0655…e8c5), finalized #11954688 (0xd435…adf0), ⬇ 1.0MiB/s ⬆ 15.8kiB/s
Apr 09 02:03:30: 2023-04-09 02:03:30 Pinned block cache limit reached. Evicting value. hash = 0xdcc8…d7f1
Apr 09 02:03:30: 2023-04-09 02:03:30 Pinned block cache limit reached. Evicting value. hash = 0x92f9…0857
Apr 09 02:03:31: ====================
Apr 09 02:03:31: Version: 0.9.41-e203bfb396e
Apr 09 02:03:31:    0: sp_panic_handler::set::{{closure}}
Apr 09 02:03:31:    1: <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
Apr 09 02:03:31:       std::panicking::rust_panic_with_hook
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
Apr 09 02:03:31:    2: std::panicking::begin_panic_handler::{{closure}}
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
Apr 09 02:03:31:    3: std::sys_common::backtrace::__rust_end_short_backtrace
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
Apr 09 02:03:31:    4: rust_begin_unwind
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
Apr 09 02:03:31:    5: core::panicking::panic_fmt
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
Apr 09 02:03:31:    6: core::result::unwrap_failed
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
Apr 09 02:03:31:    7: <sp_state_machine::ext::Ext<H,B> as sp_externalities::Externalities>::storage
Apr 09 02:03:31:    8: sp_io::storage::get_version_1
Apr 09 02:03:31:    9: sp_io::storage::ExtStorageGetVersion1::call
Apr 09 02:03:31:   10: <F as wasmtime::func::IntoFunc<T,(wasmtime::func::Caller<T>,A1),R>>::into_func::wasm_to_host_shim
Apr 09 02:03:31:   11: <unknown>
Apr 09 02:03:31:   12: <unknown>
Apr 09 02:03:31:   13: <unknown>
Apr 09 02:03:31:   14: <unknown>
Apr 09 02:03:31:   15: <unknown>
Apr 09 02:03:31:   16: <unknown>
Apr 09 02:03:31:   17: <unknown>
Apr 09 02:03:31:   18: <unknown>
Apr 09 02:03:31:   19: <unknown>
Apr 09 02:03:31:   20: <unknown>
Apr 09 02:03:31:   21: <unknown>
Apr 09 02:03:31:   22: <unknown>
Apr 09 02:03:31:   23: <unknown>
Apr 09 02:03:31:   24: wasmtime_runtime::traphandlers::catch_traps::call_closure
Apr 09 02:03:31:   25: wasmtime_setjmp
Apr 09 02:03:31:   26: sc_executor_wasmtime::runtime::perform_call
Apr 09 02:03:31:   27: <sc_executor_wasmtime::runtime::WasmtimeInstance as sc_executor_common::wasm_runtime::WasmInstance>::call_with_allocation_stats
Apr 09 02:03:31:   28: sc_executor_common::wasm_runtime::WasmInstance::call_export
Apr 09 02:03:31:   29: sc_executor::native_executor::WasmExecutor<H>::with_instance::{{closure}}
Apr 09 02:03:31:   30: <sc_executor::native_executor::NativeElseWasmExecutor<D> as sp_core::traits::CodeExecutor>::call
Apr 09 02:03:31:   31: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_aux
Apr 09 02:03:31:   32: sp_state_machine::execution::StateMachine<B,H,Exec>::execute_using_consensus_failure_handler
Apr 09 02:03:31:   33: <sc_service::client::client::Client<B,E,Block,RA> as sp_api::CallApiAt<Block>>::call_api_at
Apr 09 02:03:31:   34: <kusama_runtime::RuntimeApiImpl<__SrApiBlock__,RuntimeApiImplCall> as sp_api::Core<__SrApiBlock__>>::__runtime_api_internal_call_api_at
Apr 09 02:03:31:   35: <&sc_service::client::client::Client<B,E,Block,RA> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
Apr 09 02:03:31:   36: <sc_consensus_grandpa::import::GrandpaBlockImport<BE,Block,Client,SC> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
Apr 09 02:03:31:   37: <sc_consensus_beefy::import::BeefyBlockImport<Block,BE,Runtime,I> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
Apr 09 02:03:31:   38: <sc_consensus_babe::BabeBlockImport<Block,Client,Inner> as sc_consensus::block_import::BlockImport<Block>>::import_block::{{closure}}
Apr 09 02:03:31:   39: <alloc::boxed::Box<dyn sc_consensus::block_import::BlockImport<B>+Transaction = Transaction+Error = sp_consensus::error::Error+core::marker::Sync+core::marker::Send> as sc_consensus::block_import::BlockImport<B>>::import_block::{{closur>
Apr 09 02:03:31:   40: sc_consensus::import_queue::basic_queue::BlockImportWorker<B>::new::{{closure}}
Apr 09 02:03:31:   41: <futures_util::future::future::Map<Fut,F> as core::future::future::Future>::poll
Apr 09 02:03:31:   42: <tracing_futures::Instrumented<T> as core::future::future::Future>::poll
Apr 09 02:03:31:   43: tokio::runtime::task::raw::poll
Apr 09 02:03:31:   44: std::sys_common::backtrace::__rust_begin_short_backtrace
Apr 09 02:03:31:   45: core::ops::function::FnOnce::call_once{{vtable.shim}}
Apr 09 02:03:31:   46: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
Apr 09 02:03:31:       <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:1988:9
Apr 09 02:03:31:       std::sys::unix::thread::Thread::new::thread_start
Apr 09 02:03:31:              at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys/unix/thread.rs:108:17
Apr 09 02:03:31:   47: start_thread
Apr 09 02:03:31:   48: clone
Apr 09 02:03:31: Thread 'tokio-runtime-worker' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Database missing expected key: 0x9f646811f3131dd00114661a796db3921bb46dfd2956dd97b96ab8f39099dba7"', /usr/local/cargo/git/checkou>
Apr 09 02:03:31: This is a bug. Please report it at:
Apr 09 02:03:31:         https://github.com/paritytech/polkadot/issues/new
```

parameters:
--chain polkadot \
--database=paritydb \
--pruning archive \
--trie-cache-size 4294967296 \

**Comment by bkchr** [comment] 2023-04-11 20:09
Duplicate of: https://github.com/paritytech/polkadot/issues/7032

**Closed by bkchr** 2023-04-11 20:09 UTC
