### ISSUE TITLE
`wasm-gc` depricated, and should not be needed?

### ISSUE THREAD

**Issue by NukeManDan** [paritytech/polkadot#5681] opened 2022-06-15 17:49 UTC
https://github.com/paritytech/polkadot/blob/537145e51d5f2ec2bdd12c12ee564eb4d9224fb5/scripts/init.sh#L14

> **Note**: you probably don't need to use this project. This project is no
> longer necessary to run by hand, nor do you need the `wasm-gc` executable
> installed.
> 
> 1.    The Rust compiler now natively supports --gc-sections when linking wasm executables, which means wasm executables already have 90% of their garbage removed when coming out of the compiler.
> 1.   The wasm-pack (and wasm-bindgen) project will already run this by default for you, so there's no need to run it again.
> 
> Don't include this build! If you think you need to feel free to open an issue on wasm-pack or wasm-bindgen, as it may be a bug in one of those projects!

I wonder if the script needs this still? It is also unmaintained, and my gut says that is a reason not to use it. 

I also noticed: https://blog.rust-lang.org/2022/02/24/Rust-1.59.0.html#creating-stripped-binaries

> ```toml
> [profile.release]
> strip = "debuginfo"
> ```
> 
> This causes debuginfo to be stripped from release binaries. You can also supply "symbols" or just true to strip all symbol information where supported.

Without context, I wonder if this is related and could obviate some need for cargo-gc

**Comment by bkchr** [comment] 2022-06-15 18:27
Wasm-gc isn't required to be installed. It can be removed from the script.

**Comment by pepyakin** [comment] 2022-06-16 12:52
I think this is a dupe of https://github.com/paritytech/substrate/issues/1262

**Closed by pepyakin** 2022-06-16 12:52 UTC
Labels: Z1-question

**Comment by bkchr** [comment] 2022-06-16 18:37
This is not really a duplicate. It is about cleaning the `init.sh` script. Not sure if someone is still using this.
