### ISSUE TITLE
Hash not equal error

### ISSUE THREAD

**Issue by mariopino** [paritytech/polkadot#459] opened 2019-10-04 09:15 UTC
Hi,

Got 'Hash not equal error' errors in syslog after stop / start polkadot v0.6.0 (probably too quick). Network is Kusama CC2 and results in a corrupted database.

```
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: Hash: given=5f2842a1dce35dbabfc70e63153ae9c34d825e9081a13dd02e0d640f8966989c, expected=4fe496b64c4bf97b93c2de804be2af1af8ee1cb81b99836ec653ff23b5b2194f
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: ====================
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: Version: 0.6.0-5020fa48-x86_64-linux-gnu
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: stack backtrace:
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    0: substrate_panic_handler::set::{{closure}}
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    1: std::panicking::rust_panic_with_hook
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:              at src/libstd/panicking.rs:477
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    2: std::panicking::begin_panic
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    4: polkadot_runtime::api::dispatch
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    5: std::panicking::try::do_call
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    6: __rust_maybe_catch_panic
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:              at src/libpanic_unwind/lib.rs:80
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    7: substrate_executor::native_executor::safe_call
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    8: std::thread::local::LocalKey<T>::with
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:    9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   10: std::thread::local::LocalKey<T>::with
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   11: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_aux
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   12: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_call_with_native_else_wasm_strategy
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   13: substrate_state_machine::StateMachine<B,H,N,T,O,Exec>::execute_using_consensus_failure_handler
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   15: substrate_client::client::Client<B,E,Block,RA>::lock_import_and_run::{{closure}}
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   16: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   17: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   18: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   20: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   22: futures_executor::thread_pool::PoolState::work
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   23: std::sys_common::backtrace::__rust_begin_short_backtrace
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   24: std::panicking::try::do_call
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   25: __rust_maybe_catch_panic
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:              at src/libpanic_unwind/lib.rs:80
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:              at rustc/ddf43867a9cbb3766b48552632a602498fae2699/src/liballoc/boxed.rs:922
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:              at rustc/ddf43867a9cbb3766b48552632a602498fae2699/src/liballoc/boxed.rs:922
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:       std::sys_common::thread::start_thread
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:              at src/libstd/sys_common/thread.rs:13
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:       std::sys::unix::thread::Thread::new::thread_start
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:              at src/libstd/sys/unix/thread.rs:79
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   29: start_thread
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]:   30: __clone
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /root/.cargo/git/checkouts/substrate-7e08433d4c370a21/e0d486d/srml/executive/src/lib.rs:271
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: This is a bug. Please report it at:
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: #011https://github.com/paritytech/polkadot/issues/new
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: Hash not equal
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: 5f2842a1dce35dbabfc70e63153ae9c34d825e9081a13dd02e0d640f8966989c
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: 4fe496b64c4bf97b93c2de804be2af1af8ee1cb81b99836ec653ff23b5b2194f
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: panicked at 'Storage root must match that calculated.', /home/volt/.cargo/git/checkouts/substrate-7e08433d4c370a21/e0d486d/srml/executive/src/lib.rs:271:3
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: 2019-10-03 17:49:10 Block import error:
Oct  3 17:49:10 ubuntu-s-2vcpu-4gb-ams3-01 polkadot[18614]: Execution(Wasmi(Trap(Trap { kind: Unreachable })))
```

**Comment by bkchr** [comment] 2019-10-04 09:26
Duplicate of https://github.com/paritytech/polkadot/issues/413

**Closed by bkchr** 2019-10-04 09:26 UTC
