### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by iammelea** [paritytech/polkadot#454] opened 2019-09-30 01:20 UTC
Node stop in block and please this is a bug, open issue 
![Screenshot from 2019-09-30 03-18-40](https://user-images.githubusercontent.com/38863192/65843287-2a0e6580-e331-11e9-9dc6-5c05b44ce597.png)
![Screenshot from 2019-09-30 03-17-21](https://user-images.githubusercontent.com/38863192/65843288-2a0e6580-e331-11e9-83d9-00c2fbd00eb1.png)

After stop and start sync ok.

**Comment by bkchr** [comment] 2019-10-01 08:45
Duplicate of: https://github.com/paritytech/polkadot/issues/413

**Closed by bkchr** 2019-10-01 08:45 UTC
