### ISSUE TITLE
Error syncing after block 8949248 (Kusama)

### ISSUE THREAD

**Issue by ravi-ojha** [paritytech/polkadot#3920] opened 2021-09-24 08:46 UTC
The node was syncing well until the block `8949248`. As a first step, I tried to upgrade to the latest version. `0.9.9-1` with runtime `kusama-9090`. However, that didn't work. 

Here's the log from the startup.
```
Parity Polkadot
✌️  version 0.9.9-1-e3901b89c-x86_64-linux-gnu
❤️  by Parity Technologies <admin@parity.io>, 2017-2021
📋 Chain specification: Kusama
🏷 Node name: Elizabeth Blackburn 2
👤 Role: FULL
💾 Database: RocksDb at /home/ubuntu/KSM/chains/ksmcc3/db
⛓  Native runtime: kusama-9090 (parity-kusama-0.tx5.au2)
```

The command used:

```sh
/home/ubuntu/substrate/target/release/polkadot --name "Elizabeth Blackburn 2" --rpc-cors all --ws-port 9944 --chain kusama --base-path /home/ubuntu/KSM
```

And this is the error I see:

```
Sep 24 08:35:52 ip-10-20-0-191 polkadot[31302]: 2021-09-24 08:35:52 💤 Idle (24 peers), best: #8949574 (0xe41a…8be0), finalized #8949248 (0x102e…0032), ⬇ 50.0kiB/s ⬆ 3.1kiB/s
Sep 24 08:35:57 ip-10-20-0-191 polkadot[31302]: 2021-09-24 08:35:57 💤 Idle (24 peers), best: #8949574 (0xe41a…8be0), finalized #8949248 (0x102e…0032), ⬇ 0.5kiB/s ⬆ 1.4kiB/s
Sep 24 08:36:02 ip-10-20-0-191 polkadot[31302]: 2021-09-24 08:36:02 ⚙️  Syncing  0.0 bps, target=#9362881 (25 peers), best: #8949574 (0xe41a…8be0), finalized #8949248 (0x102e…0032), ⬇ 26.4kiB/s ⬆ 1.2kiB/s
Sep 24 08:36:05 ip-10-20-0-191 polkadot[31302]: 2021-09-24 08:36:05 💔 Error importing block 0xb33d54bea1a628a3c72f6b58dc22bca311274059767479937977ae88454b886f: Err(UnknownParent)
Sep 24 08:36:07 ip-10-20-0-191 polkadot[31302]: 2021-09-24 08:36:07 ⚙️  Syncing  0.0 bps, target=#9362882 (25 peers), best: #8949574 (0xe41a…8be0), finalized #8949248 (0x102e…0032), ⬇ 3.0MiB/s ⬆ 1.5kiB/s
Sep 24 08:36:10 ip-10-20-0-191 polkadot[31302]: 2021-09-24 08:36:10 💔 Error importing block 0xb33d54bea1a628a3c72f6b58dc22bca311274059767479937977ae88454b886f: Err(UnknownParent)
```

Am I missing something obvious? As a last resort, I even tried to nuke the whole node with data and started a fresh resync from the beginning, but it got stuck at the same block.

**Comment by bkchr** [comment] 2021-09-25 20:01
Duplicate of: https://github.com/paritytech/polkadot/issues/3778

If you want to solve it now, just use the latest rc of 0.9.10. Or download a snapshot somewhere.

**Closed by bkchr** 2021-09-25 20:01 UTC
