### ISSUE TITLE
unnamed panicked at Externalities not allowed to fail

### ISSUE THREAD

**Issue by gregzaitsev** [paritytech/polkadot#428] opened 2019-09-10 15:26 UTC
2019-09-10 15:19:36 Imported #260131 (0x3a1c…92bd)
2019-09-10 15:19:36 Starting parachain attestation session on top of parent 0x3a1c36e51493164e399e6be6f1a4fa1e50c0cf74a3f64ee5d4d09edee76492bd. Local parachain duty is None
2019-09-10 15:19:36 Idle (25 peers), best: #260131 (0x2aec…a034), finalized #260130 (0xeb5a…2379), ⬇ 24.4kiB/s ⬆ 37.0kiB/s
2019-09-10 15:19:36 Reorg from #260131,0x3a1c…92bd to #260131,0x2aec…a034, common ancestor #260130,0xeb5a…2379
2019-09-10 15:19:36 Imported #260131 (0x2aec…a034)
2019-09-10 15:19:36 Starting parachain attestation session on top of parent 0x2aec9ead7973f6ba4dde7bd0aac0357499f517194efb4583ba5e35348bcda034. Local parachain duty is None
2019-09-10 15:19:41 Idle (25 peers), best: #260131 (0x2aec…a034), finalized #260130 (0xeb5a…2379), ⬇ 25.1kiB/s ⬆ 23.7kiB/s
2019-09-10 15:19:42 Imported #260132 (0x2042…7dc9)
2019-09-10 15:19:42 Starting parachain attestation session on top of parent 0x2042fe9e996d1d7936593d5b1b6796fe507c60ac4c018a59aa653e3273957dc9. Local parachain duty is None
2019-09-10 15:19:42 Error running offchain workers at Number(260132): UnknownBlock("Number(260132)")

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h82cae3535dcc52cb (0x56512865aa50)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x565128796199)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x565128795c32)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x565128795b16)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x5651287b79cd)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::he4f9eb8cafebf37c (0x56512799755e)
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_state_machine::Externalities<H>>::storage::h2c4abf680c69a477 (0x565127795310)
   7: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index::h6b995d6f2e2632ae (0x56512762849d)
   8: wasmi::func::FuncInstance::invoke::h7894400049b38918 (0x56512752a36a)
   9: wasmi::runner::Interpreter::start_execution::hb09abc3c98c5fc95 (0x56512789570a)
  10: wasmi::func::FuncInstance::invoke::h7894400049b38918 (0x56512752a3fc)
  11: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::hce03e1215a37f12b (0x565127693bbb)
  12: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::h386b4dd0f3cdde70 (0x5651278fbe3b)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h81ff6aec886e1da2 (0x565127a4cfe0)
  14: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h1ad7c4c76a606e6a (0x565127a5f412)
  15: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hffb5021b6b64b883 (0x5651279477ab)
  16: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::h0194d1157b7f28d0 (0x5651277080f0)
  17: substrate_client::runtime_api::runtime_decl_for_Core::initialize_block_call_api_at::ha6d4eb7beadbebc6 (0x565127822f05)
  18: substrate_client::runtime_api::Core::initialize_block::h5cb1d1aac79dd77b (0x5651274cb01a)
  19: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h3e210fc92a85ba70 (0x565127935928)
  20: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::hdd26c517bfdcfb47 (0x56512770bbb7)
  21: polkadot_primitives::parachain::runtime_decl_for_ParachainHost::active_parachains_call_api_at::h0364c08d2158ef62 (0x565127a3219c)
  22: polkadot_primitives::parachain::ParachainHost::active_parachains::hf3148ca1bbaba98f (0x5651274e22ff)
  23: polkadot_validation::ParachainValidation<C,N,P>::get_or_instantiate::h175e3947db58efdd (0x5651275b3288)
  24: <futures::stream::for_each::ForEach<S,F,U> as futures::future::Future>::poll::h4679b4dba3db2d26 (0x565127adb376)
  25: <futures::future::select::Select<A,B> as futures::future::Future>::poll::h7adf13b5b6d05295 (0x5651278b7315)
  26: futures::future::chain::Chain<A,B,C>::poll::h60728e96dca08c12 (0x565127c1a559)
  27: futures::task_impl::std::set::h7fe0cb2c731179a7 (0x565127c98382)
  28: tokio_current_thread::CurrentRunner::set_spawn::h2a36d04623b9bb17 (0x5651274f11bb)
  29: tokio_current_thread::scheduler::Scheduler<U>::tick::h0f1408a23d967aba (0x565127bdb859)
  30: tokio_current_thread::Entered<P>::block_on::h2c46d3dcf9b50f3c (0x5651274f13b6)
  31: std::thread::local::LocalKey<T>::with::h463fbcadd46de3df (0x565127966374)
  32: std::thread::local::LocalKey<T>::with::hfac23ebb41a571ca (0x565127976e5b)
  33: std::thread::local::LocalKey<T>::with::h7c07fcbe75b9739d (0x56512796c16b)
  34: std::thread::local::LocalKey<T>::with::h89701d12e30854a7 (0x56512796ccd1)
  35: tokio::runtime::current_thread::runtime::Runtime::block_on::hd562e8d11e3308c2 (0x5651277688b5)
  36: std::sys_common::backtrace::__rust_begin_short_backtrace::he380c5ee40e09597 (0x565127c76113)
  37: std::panicking::try::do_call::h8d0aa7a43810ae50 (0x565127b48439)
  38: __rust_maybe_catch_panic (0x56512879f0ba)
             at src/libpanic_unwind/lib.rs:82
  39: core::ops::function::FnOnce::call_once{{vtable.shim}}::h579f9a08af48d769 (0x5651275dfcc4)
  40: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x56512878427f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  41: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x56512879e440)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  42: start_thread (0x7f178943b4a4)
  43: __clone (0x7f1788f66d0f)
  44: <unknown> (0x0)

Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0xe41d6df85da5f35adc656f80034de4324802f8b5313bae463ee43f2db28374a8"', src/libcore/result.rs:999

This is a bug. Please report it at:

	https://github.com/paritytech/polkadot/issues/new

**Comment by dbpatty** [comment] 2019-10-01 19:31
me too

**Comment by bkchr** [comment] 2019-10-29 13:04
Duplicate of: https://github.com/paritytech/polkadot/issues/419

**Closed by bkchr** 2019-10-29 13:04 UTC

**Comment by dbpatty** [comment] 2019-10-29 20:23
thank you
