### ISSUE TITLE
Trie lookup error: Invalid state root

### ISSUE THREAD

**Issue by chrishobcroft** [paritytech/polkadot#435] opened 2019-09-14 11:59 UTC
Kusama Validator node crashed this morning.

Here's the stack backtrace:

```
2019-09-14 07:18:07 Starting parachain attestation session on top of parent 0xb422651dbc02783c2eae75d92916a236a44aa03380597c1e56a6e2a972e7ccd9. Local parachain duty is None
2019-09-14 07:18:07 Imported #312539 (0xb422…ccd9)

====================

stack backtrace:
   0: substrate_panic_handler::set::{{closure}}::h82cae3535dcc52cb (0x557606a671c0)
   1: std::panicking::rust_panic_with_hook::hffcefc09751839d1 (0x557606ba58a9)
             at src/libstd/panicking.rs:481
   2: std::panicking::continue_panic_fmt::hc0f142c930c846fc (0x557606ba5342)
             at src/libstd/panicking.rs:384
   3: rust_begin_unwind (0x557606ba5226)
             at src/libstd/panicking.rs:311
   4: core::panicking::panic_fmt::h2daf88b2616ca2b2 (0x557606bc70dd)
             at src/libcore/panicking.rs:85
   5: core::result::unwrap_failed::h62dbd5a8e5560593 (0x557605dbae2e)
   6: <substrate_state_machine::ext::Ext<H,N,B,T,O> as substrate_state_machine::Externalities<H>>::storage::hb493a5df659ab9f3 (0x557605a88aa0)
   7: <substrate_executor::wasm_executor::FunctionExecutor<E> as wasmi::host::Externals>::invoke_index::hb45ea024086571d1 (0x55760596339d)
   8: wasmi::func::FuncInstance::invoke::h5b09d54c708b1b31 (0x557605823bda)
   9: wasmi::runner::Interpreter::start_execution::h4858fcd74c407050 (0x557605b87548)
  10: wasmi::func::FuncInstance::invoke::h5b09d54c708b1b31 (0x557605823c6c)
  11: substrate_executor::wasm_executor::WasmExecutor::call_in_wasm_module::h07b2a5c593c7addf (0x55760598d897)
  12: <substrate_executor::native_executor::NativeExecutor<D> as substrate_state_machine::CodeExecutor<substrate_primitives::hasher::blake2::Blake2Hasher>>::call::heef7ff72239b90f2 (0x557605c1675b)
  13: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_aux::h40e0fef5aad580f3 (0x557605d3ead0)
  14: substrate_state_machine::StateMachine<H,N,B,T,O,Exec>::execute_using_consensus_failure_handler::h260d5fc78a88d573 (0x557605d5ce30)
  15: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::hc9d14c9a3c6e6a24 (0x557605c34dab)
  16: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::hbf93113da3de111a (0x5576058949aa)
  17: <polkadot_runtime::RuntimeApiImpl<RuntimeApiImplCall> as substrate_client::runtime_api::Core<<polkadot_runtime::Runtime as sr_primitives::traits::GetNodeBlockType>::NodeBlock>>::Core_initialize_block_runtime_api_impl::hb7bdde40663ba0bc (0x5576057ef379)
  18: substrate_client::runtime_api::Core::initialize_block::hb74ada721fa5e557 (0x5576057b4817)
  19: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::contextual_call::h0e184167ad262d2e (0x557605c243dd)
  20: <substrate_client::client::Client<B,E,Block,RA> as substrate_client::runtime_api::CallRuntimeAt<Block>>::call_api_at::hcff21ce0e7326f2f (0x557605894cd4)
  21: substrate_offchain_primitives::runtime_decl_for_OffchainWorkerApi::offchain_worker_call_api_at::h17e0e25eaca8b785 (0x5576059dcc79)
  22: substrate_offchain_primitives::OffchainWorkerApi::offchain_worker_with_context::hfbf1669aaeb84646 (0x5576057f36a3)
  23: std::sys_common::backtrace::__rust_begin_short_backtrace::h98de425815565993 (0x5576058df07e)
  24: std::panicking::try::do_call::h6c77293866d7abf7 (0x557605e3e2a4)
  25: __rust_maybe_catch_panic (0x557606bae7ca)
             at src/libpanic_unwind/lib.rs:82
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}::hf89fd3fc7704fa0f (0x5576059e7953)
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h42806b83647d4c79 (0x557606b9364f)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once::h83c921c8e826dd1d (0x557606badb50)
             at /rustc/eae3437dfe991621e8afdc82734f4a172d7ddf9b/src/liballoc/boxed.rs:746
      std::sys_common::thread::start_thread::h2613204ce513782e
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start::h4570080769500bcd
             at src/libstd/sys/unix/thread.rs:79
  29: start_thread (0x7fd50af3d6db)
  30: __clone (0x7fd50aa4e88f)
  31: <unknown> (0x0)

Thread '<unnamed>' panicked at 'Externalities not allowed to fail within runtime: "Trie lookup error: Invalid state root: 0x9dc2559aa0a1ffe1ba4ef4fcb99220442908bb543022d4bca8bf1539f541b131"', src/libcore/result.rs:999

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

```

**Comment by bkchr** [comment] 2019-09-26 07:38
Duplicate of https://github.com/paritytech/polkadot/issues/419

**Closed by bkchr** 2019-09-26 07:38 UTC
