### ISSUE TITLE
Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.'

### ISSUE THREAD

**Issue by sweetpotatoz** [paritytech/polkadot#503] opened 2019-10-28 07:31 UTC
Version: 0.6.3-1d890239-x86_64-linux-gnu
Run command:
docker run -v kusama:/polkadot parity/polkadot:latest --validator --name "<name>" --pruning=archive
Error log as below

```
stack backtrace:
   0: substrate_panic_handler::set::{{closure}}
   1: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:481
   2: std::panicking::begin_panic
   3: srml_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
   4: polkadot_runtime::api::dispatch
   5: std::panicking::try::do_call
   6: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
   7: substrate_executor::native_executor::safe_call
   8: std::thread::local::LocalKey<T>::with
   9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
  10: std::thread::local::LocalKey<T>::with
  11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
  12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
  13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
  14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
  15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
  18: substrate_consensus_common::import_queue::import_single_block
  19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  20: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
  21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
  22: futures_executor::thread_pool::PoolState::work
  23: std::sys_common::backtrace::__rust_begin_short_backtrace
  24: std::panicking::try::do_call
  25: __rust_maybe_catch_panic
             at src/libpanic_unwind/lib.rs:80
  26: core::ops::function::FnOnce::call_once{{vtable.shim}}
  27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
  28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
             at rustc/625451e376bb2e5283fc4741caa0a3e8a2ca4d54/src/liballoc/boxed.rs:787
      std::sys_common::thread::start_thread
             at src/libstd/sys_common/thread.rs:13
      std::sys::unix::thread::Thread::new::thread_start
             at src/libstd/sys/unix/thread.rs:79
  29: start_thread
  30: __clone


Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /ci-cache/polkadot/cargo/build-linux-release/git/checkouts/substrate-7e08433d4c370a21/4a13f61/srml/executive/src/lib.rs:271

This is a bug. Please report it at:

        https://github.com/paritytech/polkadot/issues/new

Hash not equal
d8c1ea744329fc5359150f7388cd801f53987292404490e1375ff9cf15adc760
33829a696c75991b4746b080d433b651d433e4cebeba939d4379bd750a13d3ed
panicked at 'Storage root must match that calculated.', /Users/gav/.cargo/git/checkouts/substrate-7e08433d4c370a21/4a13f61/srml/executive/src/lib.rs:271:3
2019-10-28 07:28:05 Block import error:
Execution(Wasmi(Trap(Trap { kind: Unreachable })))
2019-10-28 07:28:07 Verification failed from peer: Could not fetch epoch at 0x586629450bf071e7eca85ceb9f532344d3f3f86260c802d08a6bd37e83962d56
2019-10-28 07:28:08 Syncing  0.0 bps, target=#441622 (14 peers), best: #424659 (0x3b3d…3c76), finalized #424659 (0x3b3d…3c76), ⬇ 35.3kiB/s ⬆ 163.2kiB/s
2019-10-28 07:28:13 Syncing  0.0 bps, target=#441623 (15 peers), best: #424659 (0x3b3d…3c76), finalized #424659 (0x3b3d…3c76), ⬇ 9.7kiB/s ⬆ 193.2kiB/s
```

**Comment by bkchr** [comment] 2019-10-28 08:01
Duplicate of: https://github.com/paritytech/polkadot/issues/413

Please use the search next time :)

**Closed by bkchr** 2019-10-28 08:01 UTC
