### ISSUE TITLE
Parachain block time degradation since v0.9.16 on Kusama

### ISSUE THREAD

**Issue by crystalin** [paritytech/polkadot#4911] opened 2022-02-11 21:10 UTC
We are observing pretty impactful degradation on Moonriver since the deployment of client v0.9.16 on Kusama.
Additionally, we have upgraded few days after Moonriver to support v0.9.16 but it had no impact.

We have been able to reproduce that on our public Alphanet (20 controlled validators, on v0.9.16)
Here are the logs for a given block not being included #1690751
[alphanet-block-degradation-block-1690751.log](https://github.com/paritytech/polkadot/files/8051641/alphanet-block-degradation-block-1690751.log)

Here is the graph showing the average time block over the last 7 days:
![image](https://user-images.githubusercontent.com/329248/153670539-0da719fa-26e8-42ca-91d8-6dd2258c9567.png)
(The spike is only the restart of our nodes, ignore it)

**Comment by crystalin** [comment] 2022-02-12 15:42
On our Alphanet, where we also observe the bug, we can see some important changes in the Validator <-> Collator peer system:
![image](https://user-images.githubusercontent.com/329248/153717866-5a7c34a6-5e59-4900-a91b-efcfd7ce9250.png)

**Comment by crystalin** [comment] 2022-02-12 17:56
Looking more deeply into the connections, here are 2 of the validators (modified to have 500 collation peer set).
![image](https://user-images.githubusercontent.com/329248/153722487-e84b23f1-4ae6-4e30-b36c-494cc7c35a76.png)
The surprising part is that it establish 100+ connection instantly and removes it

**Comment by crystalin** [comment] 2022-02-12 18:12
I've done some test, and I suspect the nodes are getting overloaded with connections in critical times. Using unoptimized binary is making the result worse also. That would explain why Kusama network is doing worse than Polkadot at the moment

**Comment by crystalin** [comment] 2022-02-12 18:27
It might be related to some optimizations @eskimor has done around collation networking

**Comment by rphmeier** [comment] 2022-02-13 01:09
Yeah, we are trying a branch with those commits removed.

**Comment by rphmeier** [comment] 2022-02-13 01:26
https://github.com/paritytech/polkadot/pull/4640/files#r805223564

**Comment by crystalin** [comment] 2022-02-13 02:07
@rphmeier Ok I'm trying it now, I'll see if this can be deployed now or will have to wait tomorrow morning

**Comment by crystalin** [comment] 2022-02-13 02:09
@rphmeier Can it be applied only to validator or do the collator also need it ?

**Comment by rphmeier** [comment] 2022-02-13 02:17
@crystalin Specifically the collators need it. This should only affect collator logic.

**Comment by crystalin** [comment] 2022-02-13 02:37
@rphmeier Yes it began while we were still on 0.9.13 collators.
Also we can't easily upgrade all our collators to a custom version. Purestake only control 8 collators out of 80.

**Comment by crystalin** [comment] 2022-02-13 03:04
Thank you @xlc , We also observed on some of our networks a small increase when the collators upgraded to support v0.9.16, but it was very small compared to the increase of block time since Kusama upgraded to v0.9.16

**Comment by crystalin** [comment] 2022-02-14 00:54
@rphmeier I tried to look more at the charts. I confirm the connection spikes happen when the validator get in the parachain core set. I had initially the idea that it could have been triggered by other parachains migrating to v0.9.16 on Kusama, but I don't think that is the case anymore.
One thing that I'd like to verify but I don't have the full data is if the validator/collator established connection started to rise/spike when the validator was upgraded on Kusama. Let me know if you can check that

**Comment by stechu** [comment] 2022-02-14 17:54
We can confirm that we observe similar issue in Calamari.

**Comment by rphmeier** [comment] 2022-02-14 23:46
https://github.com/paritytech/substrate/compare/polkadot-v0.9.15...polkadot-v0.9.16

These are all Substrate changes from that period

https://github.com/paritytech/polkadot/compare/v0.9.15...v0.9.16

These are all Polkadot changes.

It seems that we're looking for stuff that is relevant to the validator nodes and excluding the runtime. That narrows things down a decent bit.
 - There are a few changes to PVF execution that could be investigated.
 - There was a sync change to better support the disputes fork-choice rule. That might have had unintended side effects
 - Changes to peer-set management for full/light nodes
 - Changes to `substrate-executor` stack guards
 - Sync changes relevant to fast/warp sync, possibly introducing bugs
 - Maybe other stuff I'm missing

**Comment by crystalin** [comment] 2022-02-15 00:38
@rphmeier I've double checked again today, but on our Alphanet, the degradation didn't start on the relay client upgrade v0.9.16 but the day after when we upgraded our collators to v0.9.16.
This contradicts with what was observed on Moonriver/Kusama (the degradation happened 1 week before we upgraded collators to v0.9.16)

I'm not sure what could trigger those 2 scenarios. Either some networking conditions that could have been triggered on Kusama earlier due to its size, and was re-enforced by upgraded parachain clients to v0.9.16 (which would have triggered it on Alphanet).

@rphmeier is it safe to revert validators to v0.9.15 on Alphanet with runtime 9160 ? (I know there is a new host, but I'm not sure if/when it is actually used)

**Comment by rphmeier** [comment] 2022-02-15 00:40
> is it safe to revert validators to v0.9.15 on Alphanet with runtime 9160 ? (I know there is a new host, but I'm not sure if/when it is actually used

I don't think so.

**Comment by crystalin** [comment] 2022-02-15 00:40
@rphmeier also are there any log (we could enable debug for all modules for a short amount of time) on our validators that would help to identify the issue ?

**Comment by rphmeier** [comment] 2022-02-15 01:20
Can we get a graph on Grafana indicating the amount of reorgs?

**Comment by crystalin** [comment] 2022-02-15 01:30
I don't have the graph, but counting the number of re-org from logs:
```
   1511 - 07
   1720 - 08
   1846 - 09
   1776 - 10
   1739 - 11
   1736 - 12
   1690 - 13
   1716 - 14
```
Those are counts per day for alphanet.
The relay v0.9.16 was deployed on Feb 09, and the parachain v0.9.16 was deployed on Feb 10

Nothing seems unusual

**Comment by crystalin** [comment] 2022-02-15 01:53
@rphmeier I realize... that actually the re-org message only applies in some cases, but the problematic one, where mutliple blocks of the same height (best) is received is not triggering a reorg:
```
Feb 15 01:50:49 moonzone alphanet[715669]: 2022-02-15 01:50:49 [🌗] 💤 Idle (50 peers), best: #1703428 (0x7662…d0a3), finalized #1703428 (0x7662…d0a3), ⬇ 2.6kiB/s ⬆ 3.4kiB/s
Feb 15 01:50:49 moonzone alphanet[715669]: 2022-02-15 01:50:49 [Relaychain] 💤 Idle (49 peers), best: #3765514 (0x6a92…ce67), finalized #3765511 (0xc386…804b), ⬇ 45.5kiB/s ⬆ 42.0kiB/s
Feb 15 01:50:50 moonzone alphanet[715669]: 2022-02-15 01:50:50 [🌗] ✨ Imported #1703429 (0x45fe…8833)
Feb 15 01:50:51 moonzone alphanet[715669]: 2022-02-15 01:50:51 [🌗] ✨ Imported #1703429 (0x8031…1937)
Feb 15 01:50:54 moonzone alphanet[715669]: 2022-02-15 01:50:54 [Relaychain] ✨ Imported #3765515 (0xecaf…b642)
Feb 15 01:50:54 moonzone alphanet[715669]: 2022-02-15 01:50:54 [Relaychain] Could not retrieve session info from rolling session window relay_parent=0xecaf63d126f6be576673de500912b82f8838505294d4acaf1d6097af218cb642
Feb 15 01:50:54 moonzone alphanet[715669]: 2022-02-15 01:50:54 [🌗] 💤 Idle (50 peers), best: #1703428 (0x7662…d0a3), finalized #1703428 (0x7662…d0a3), ⬇ 293.7kiB/s ⬆ 1.2MiB/s
Feb 15 01:50:54 moonzone alphanet[715669]: 2022-02-15 01:50:54 [Relaychain] 💤 Idle (49 peers), best: #3765515 (0xecaf…b642), finalized #3765512 (0x13e4…e778), ⬇ 63.1kiB/s ⬆ 30.1kiB/s
```

As you can see here, there are 2 `Imported #1703429` with different hash, usually prevent the parachain to get the block produced/included in time. I'll see if I can count them

**Comment by gilescope** [comment] 2022-02-15 09:12
Here's the block times for statemine - on the left is before the upgrade and on the right is after. It's pretty clear that block production has taken a hit:
![Screenshot(29)](https://user-images.githubusercontent.com/803976/154029359-65bfa704-73b8-4402-aa2d-126c1b5d0dfd.png)

(There's probably a better graph out there but this is the one I have to hand)

**Comment by ordian** [comment] 2022-02-15 14:21
We'd like to include https://github.com/paritytech/polkadot/pull/4914 into the next release (and collators as well), even though it doesn't explain all of the issues we're observing here.

**Comment by crystalin** [comment] 2022-02-15 14:58
Adding additional information. 

We can't reproduce it with small networks (<20 collators). Here are the affected networks selected collators count (there are more collators but those are the one producing blocks):
 * Alphanet: 100 (internal relay, 21 validators)
 * Moonriver: 64 (kusama)
 * Moonbeam 53 (polkadot)
(Each network has 300+ nodes)

Here is Moonbeam block time over the last days. It has also degradated:
![image](https://user-images.githubusercontent.com/329248/154087781-d082fd8e-55d5-4014-987c-d894641a5ac4.png)
(spikes are just node reboots, to be ignored)

It matches with the collators deploying v0.9.16 support. We are asking them to revert to previous version (v0.9.13) to see if it impacts (until runtime 9160 is deployed on Polkadot)

**Comment by crystalin** [comment] 2022-02-15 18:31
Reverting many (not all) collators to v0.19.2 (using substrate v0.9.13) had an initial impact but it came back to the same degradation level as it was before:
![image](https://user-images.githubusercontent.com/329248/154126122-7fd10223-f642-4700-b3d8-bc86ff116486.png)
(The vertical bar is when our nodes downgraded)

We are testing to reduce active collator from 100 to 30 on Alphanet to see if there is an impact

**Comment by crystalin** [comment] 2022-02-15 20:10
Waiting a bit more. This is Moonbeam data
![image](https://user-images.githubusercontent.com/329248/154141038-c6d421ae-261e-4856-9a79-4eb89a416024.png)

**Comment by crystalin** [comment] 2022-02-16 01:32
Reducing Alphanet selected Collator from 100 to 30 didn't change the block time degradation.

**Comment by crystalin** [comment] 2022-02-16 02:47
We've tweaked one of our internal network (stagenet) to have 50 collators (on v0.9.16 support) but with only 8 selected to produce blocks (always the same).
(The relay is 0.9.16 with 9160 westend composed of 8 validators)

The block time increased:
![image](https://user-images.githubusercontent.com/329248/154186677-8cadf86c-890b-4f18-9a39-44722b9d13bd.png)

That means that even when collators are not producing blocks they are impacting the block time (@rphmeier)

**Comment by koute** [comment] 2022-02-16 07:40
@crystalin Just to make absolutely sure we're measuring the same thing can you please share your Grafana query you're using to produce that "Block Time [60m]" graph?

**Comment by gilescope** [comment] 2022-02-16 08:08
![Screenshot(31)](https://user-images.githubusercontent.com/803976/154221733-14ca9711-72e9-4761-b089-1074b04873ec.png)

It looks like the rollback of that PR seems to improve block times on westmint (unless I have messed up the query). This is looking at the last 7 days on westmint. The PR rolls back a noisy warning as well so the right hand warning graph makes it clear when the rolled back PR was introduced.

**Comment by ordian** [comment] 2022-02-16 12:13
From the data on Rococo, we can see a degradation in the collator protocol:
![image](https://user-images.githubusercontent.com/4211399/154261922-fbf847d0-092a-4d2b-ac43-6f6d705675bd.png)
![image](https://user-images.githubusercontent.com/4211399/154261926-188300b9-3586-4161-86be-60ff9131d7a7.png)

with `Collation wasn't advertised to any validator.` logs increase on collators. Inclusion times seem unaffected.
Our data suggests that applying https://github.com/paritytech/polkadot/pull/4925 with https://github.com/paritytech/polkadot/pull/4925#discussion_r807000553 to validators and https://github.com/paritytech/cumulus/pull/990 to collators will bring the parablock times to the previous value.

**Comment by Mitchell-Grimes** [comment] 2022-02-16 13:52
> ![Screenshot(31)](https://user-images.githubusercontent.com/803976/154221733-14ca9711-72e9-4761-b089-1074b04873ec.png)
> 
> It looks like the rollback of that PR seems to improve block times on westmint (unless I have messed up the query). This is looking at the last 7 days on westmint. The PR rolls back a noisy warning as well so the right hand warning graph makes it clear when the rolled back PR was introduced.

Hey, the query is `sum(1/rate(substrate_block_height{pod=~"$workload",chain=~"(moonbeam-|)$network(net|)"
,endpoint="$chain",status="best"}[60m])) by (pod)`
![image](https://user-images.githubusercontent.com/52660893/154278576-0c7046c7-583d-450e-98a1-10a61ceff37d.png)

**Comment by sander2** [comment] 2022-02-16 14:14
Just as an additional datapoint: these are the block production times on kintsugi. You can see a big increase on feb 8, even though we did not upgrade our nodes until feb 11th.
![image](https://user-images.githubusercontent.com/2421693/154282383-b66acdfe-79db-4b63-9f35-d3c4c418cf9f.png)

(graph created with `avg(5*60/increase(substrate_block_height{kubernetes_namespace="interbtc-kusama",status="finalized"}[5m]))`)

**Comment by rphmeier** [comment] 2022-02-16 21:32
Based on the data and experiments so far we have 2 further tests planned to confirm the fix:
  * Deploy https://github.com/paritytech/polkadot/pull/4925#discussion_r807000553 on Rococo with a parachain that has 50 validators.
  * Deploy to Westend

**Comment by rphmeier** [comment] 2022-03-02 21:08
I dug into Statemine's performance. There are sharp differences observable in the behavior of the collators.

## Collator Metrics

<img width="1652" alt="image" src="https://user-images.githubusercontent.com/10121380/156445704-ba6a7d48-bc76-49f8-85fc-d62227ad1417.png">

The green line is the number of advertisements made by collators. The yellow line is the number of advertised collations requested by validators. And the blue line is the number of collations generated.

## Collator Versions

<img width="1651" alt="image" src="https://user-images.githubusercontent.com/10121380/156447122-966d14c0-3afd-4498-bbf1-8dc94ecc7cf1.png">


## Initial Observations

1. All graphs exhibit 3 points of decline: a slow decline starting Feb 4, a subsequent drop on Feb 7, and a final drop on Feb 10. After this point, behavior improves. 0.9.16 was released on Feb 4
2. All graphs exhibit a subsequent increase on Feb 23-25. 0.9.17 was released on Feb 23.
3. The advertisements / requests graphs have dropped after the collators upgraded on Feb 28/Mar 1 despite number of collations remaining steady.
4. The amount of advertisements made overall has an expected reduction by 1/2 after changing the behavior of collators not to advertise their collations to the validators of the next validator group. That is, collators now only advertise to one group and not two.
5. The number of produced collations has recovered somewhat to pre-0.9.16 levels after the upgrade to 0.9.17. This might be explained by longer availability distribution times on Kusama (as discussed in #5021)

## Proportion of Advertisements Requested

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/10121380/156448358-b0929d68-a71e-4d5c-883e-24d4c38d20f7.png">

We can see a sharp jump up to ~90% after statemine collators were upgraded to 0.9.16 on Feb 10.
Before then, half of advertisements were redundant. With that in mind, the real ratio of requests:advertisements was about 100-105% prior to Feb 4. This indicates that something is causing validators to be 10-15% less likely on average to request an advertised collation.

## Normalized to Validator Group Sizes

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/10121380/156449217-10c23605-978c-4b60-9ecf-2ad61c8cdef6.png">

Here is a normalized version of the first graph where the advertisements and requests graphs are normalized by a factor of 5, to account for the fact that Kusama validator groups have 5 validators in them. So this represents "advertisements/requests per validator in group" as compared to collations, as opposed to "total advertisements/requests".

Again, we see the same drop-off where previous to 0.9.16 on Feb 10, only half of advertisements were requested and this is because only half of advertisements were to validators that would act on them.

The number of requests per collation per validator has degraded from around 2/3 to 1/2 and the number of requested collations per validator have degraded by 1/2 in absolute terms.

**Comment by rphmeier** [comment] 2022-03-03 06:37
I had a bit of time so I took a sample of the amount of time spent in availability (this was on Moonriver) on Kusama before 0.9.16 and from earlier today, and found that this changed from 1.0569 blocks to 1.8742 blocks, which is a 77.3% increase. This explains 6*.773=4.64s of reduced block time.

**Comment by Lldenaurois** [comment] 2022-03-07 19:21
After aligning with the Purestake team, we were able to reproduce lapses in block times on Versi.

Originally, we added 200ms latency to the chaos network for Versi and immediately experienced large lapses in parachain block times. In addition, relay chain block times were regularly 12s and spike to 18s at times.

The largest lapse in parachain blocks was approximately 3 mins.

In order to further our hypothesis, we removed the latency entirely and observed the relay chain block times. To our surprise, we still observed similar relay chain block times (though more infrequent than previously).

Specifically, we can observe large lapses in bitfield-signing as can be confirmed here: https://grafana.parity-mgmt.parity.io/goto/eAnc-LYnz?orgId=1 (flip results order to observe large time-spans of `false` availability for the first core).

Looking into the computation for that particular boolean, we observe [here](https://github.com/paritytech/polkadot/blob/master/node/core/bitfield-signing/src/lib.rs#L84) that false can only be achieved if

1. The core is Available
2. The core is Scheduled
3. The core is Occupied and the Chunk is unavailable for the node keystore's particular validator_idx

Example: https://grafana.parity-mgmt.parity.io/goto/VlJ4BYY7z?orgId=1 (flip results order)

We observe large spurts of the `signing-bitfield` log line reporting `false` for the first core (the one Moonbeam is assigned to). However, if we verify the `TRACE` statements in this same time-frame (see https://grafana.parity-mgmt.parity.io/goto/2ykKfYY7k?orgId=1), we observe no trace lines whatsoever.

This concludes that the core is not Occupied (it is either Scheduled or Fee), as we would otherwise expect to see a log line for the `QueryChunkAvailability` response.

If the core is not occupied, it stands to reason that the collators are in some way misinterpreting this information and not producing collations even though the core is being reported as free for all validators.

During this time, we observe large outages in approval-distribution noting that an assignment from a peer is out of view: (https://grafana.parity-mgmt.parity.io/goto/st34YLLnz?orgId=1). 

An important observation from this analysis is that the long relay-chain block times were not fixed by removing the chaos network latency.

A noteworthy mention is that one of the validators seems to have crashed at some point (but is now running fine): https://grafana.parity-mgmt.parity.io/goto/-yrMYYL7k?orgId=1

**Comment by rphmeier** [comment] 2022-03-18 16:36
<img width="826" alt="image" src="https://user-images.githubusercontent.com/10121380/159043622-7628bd7c-eb11-4c7a-91d1-e7c2302d4750.png">

^ average time-in-flight for intra-node messages being sent to the approval-distribution subsystem. This appears to cause a cascading effect causing other network subsystems to slow down.

<img width="1644" alt="image" src="https://user-images.githubusercontent.com/10121380/159043841-8d5ad59a-06a5-4a70-9d87-a9c265fc9d51.png">

^ Nodes are receiving massive amounts of intra-node messages on the approval-distribution subsystem, far beyond the expected amounts. These probably originate in the network, but might originate in the approval-voting subsystem. Nodes are sending tons of messages to the network-bridge.

<img width="1645" alt="image" src="https://user-images.githubusercontent.com/10121380/159044267-be70807d-9075-4fe0-9d06-4ac6b39b2214.png">

^ This shows that the number of notifications received on the network corresponds very closely to the approval-distribution subsystem, indicating that the messages originate in the network. The gap represents messages from other subsystems.

Optimizing approval-distribution will probably help.

**Comment by gilescope** [comment] 2022-06-20 11:06
Can we close this issue now?

**Comment by crystalin** [comment] 2022-06-20 13:59
Well, I don't think the issue is fully resolved. @rphmeier , Currently on Moonriver, block average time is around 14s (as opposed to 12.5s on Moonbeam), so I think there is still improvement to be done, what do you think ?

**Comment by crystalin** [comment] 2022-06-20 14:05
FYI: This is what it looks for the last 90 days:
![image](https://user-images.githubusercontent.com/329248/174619435-c3fdfe87-d023-43ca-ac52-35d9d91de7d8.png)

**Comment by rphmeier** [comment] 2022-10-26 22:15
Going to close this; the next round of improvements will come with asynchronous backing.

**Closed by rphmeier** 2022-10-26 22:15 UTC
