### ISSUE TITLE
Docker container running kusama doesn't restart on crash

### ISSUE THREAD

**Issue by JonasPf** [paritytech/polkadot#605] opened 2019-11-22 17:20 UTC
Related to #604. There was a crash in kusama. We are running kusama in a docker container. After the crash the docker container did not restart. I think (but am not sure) that this is due to the fact that kusama doesn't exit with a proper exit code (!=0).

From an operations perspective it might be desirable to just exit and let the parent process decide whether to restart. This would work with docker or systemd or any other watchdog.

Please note that we use a different Dockerfile (https://github.com/polkasource/substrate-client/blob/kusama/Dockerfile) and not the one from this repository. I don't think it matters but if this is the wrong place, please close this ticket and I'll open a new one in the polkasource repository.

**Comment by bkchr** [comment] 2019-12-07 22:18
Sounds more like an issue on your side. Docker containers do not restart automatically, you need to configure this explicitly for a container.

**Comment by JonasPf** [comment] 2019-12-28 13:14
Well, in this case the containers where started with `restart=unless-stopped`. I believe the problem is that the process inside docker didn't exit with a proper exit code.

**Comment by bkchr** [comment] 2019-12-30 13:43
We exit with `1` when there is a panic. So, I'm not sure why it did not restart. I still suspect docker. Do you have the output of the container that did not restart?

**Comment by chevdor** [comment] 2020-03-18 09:14
I agree with @bkchr. I did the following tests (not using the same image but that should be close enough):
`docker run --name test -d -it chevdor/polkadot:0.7.20 polkadot --port 98798798798`

The port being invalid, that makes polkadot rather unhappy and it returns 1:
```
$ polkadot --port 98798798798; echo $?
error: Invalid value for '--port <PORT>': number too large to fit in target type
1
```

The container will stop and not restart. After that, killed it:
`rm -f test`
and restarted it with your restart option:
```
docker run --name test -d -it --restart=unless-stopped chevdor/polkadot:0.7.20 polkadot --port 98798798798
```

Now the container keeps on restarting as expected.

So either you have an issue regarding how you use the `restart` option or you found a case where the assumption of @bkchr is wrong. 

If you can reproduce the issue, the best would be to check the exit code.
Can you share the exact docker command you used ?

**Comment by chevdor** [comment] 2020-03-18 09:26
Here is a snippet that should help if you can reproduce the issue:
```
docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port -1; echo $?"
```

Note that, depending on the error, the exit code may be 0 or not and that will condition whether or not your container restart. I cannot say more without knowing the options you passed.

Here are a few samples:
```
$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port -1; echo $?"
error: Found argument '-1' which wasn't expected, or isn't valid in this context

USAGE:
    polkadot --port <PORT>

For more information try --help
0                                                               <==== Here we get 0
```

I did hit a strange case though. Below is my raw output:

```
$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 987987987; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
0
10:22 substrate (master)*$ 
^C
10:22 substrate (master)*$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 98798798798; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
1                                            <=== 😲
10:22 substrate (master)*$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 987987987; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
0
10:23 substrate (master)*$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 98798798798; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
0
10:23 substrate (master)*$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 98798798798; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
0
10:23 substrate (master)*$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 98798798798; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
0
10:23 substrate (master)*$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 987987987; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
0
10:23 substrate (master)*$ docker run --rm -it chevdor/polkadot:0.7.20 bash -c "polkadot --port 98798798798; echo $?"
error: Invalid value for '--port <PORT>': number too large to fit in target type
0

```

**Comment by bkchr** [comment] 2020-03-27 21:51
There was no update since november, I will close this issue. Please reopen if this issue still exists.

**Closed by bkchr** 2020-03-27 21:51 UTC
Labels: F8-enhancement
