### ISSUE TITLE
Storage root mismatch

### ISSUE THREAD

**Issue by BCpowerup** [paritytech/polkadot#610] opened 2019-11-23 16:57 UTC
Nov 23 16:49:59 polkadot-london polkadot[17082]: ====================
Nov 23 16:49:59 polkadot-london polkadot[17082]: Version: 0.6.17-4b9ed4e1-x86_64-linux-gnu
Nov 23 16:49:59 polkadot-london polkadot[17082]: stack backtrace:
Nov 23 16:49:59 polkadot-london polkadot[17082]:    0: substrate_panic_handler::set::{{closure}}
Nov 23 16:49:59 polkadot-london polkadot[17082]:    1: std::panicking::rust_panic_with_hook
Nov 23 16:49:59 polkadot-london polkadot[17082]:              at src/libstd/panicking.rs:477
Nov 23 16:49:59 polkadot-london polkadot[17082]:    2: std::panicking::begin_panic
Nov 23 16:49:59 polkadot-london polkadot[17082]:    3: paint_executive::Executive<System,Block,Context,UnsignedValidator,AllModules>::execute_block
Nov 23 16:49:59 polkadot-london polkadot[17082]:    4: polkadot_runtime::api::dispatch
Nov 23 16:49:59 polkadot-london polkadot[17082]:    5: std::panicking::try::do_call
Nov 23 16:49:59 polkadot-london polkadot[17082]:    6: __rust_maybe_catch_panic
Nov 23 16:49:59 polkadot-london polkadot[17082]:              at src/libpanic_unwind/lib.rs:80
Nov 23 16:49:59 polkadot-london polkadot[17082]:    7: substrate_executor::native_executor::safe_call
Nov 23 16:49:59 polkadot-london polkadot[17082]:    8: std::thread::local::LocalKey<T>::with
Nov 23 16:49:59 polkadot-london polkadot[17082]:    9: <polkadot_executor::Executor as substrate_executor::native_executor::NativeExecutionDispatch>::dispatch
Nov 23 16:49:59 polkadot-london polkadot[17082]:   10: std::thread::local::LocalKey<T>::with
Nov 23 16:49:59 polkadot-london polkadot[17082]:   11: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_aux
Nov 23 16:49:59 polkadot-london polkadot[17082]:   12: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_call_with_native_else_wasm_strategy
Nov 23 16:49:59 polkadot-london polkadot[17082]:   13: substrate_state_machine::StateMachine<B,H,N,T,Exec>::execute_using_consensus_failure_handler
Nov 23 16:49:59 polkadot-london polkadot[17082]:   14: <substrate_client::call_executor::LocalCallExecutor<B,E> as substrate_client_api::call_executor::CallExecutor<Block,substrate_primitives::hasher::blake2::Blake2Hasher>>::call_at_state
Nov 23 16:49:59 polkadot-london polkadot[17082]:   15: <&substrate_client::client::Client<B,E,Block,RA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 23 16:49:59 polkadot-london polkadot[17082]:   16: <substrate_finality_grandpa::import::GrandpaBlockImport<B,E,Block,RA,SC> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 23 16:49:59 polkadot-london polkadot[17082]:   17: <substrate_consensus_babe::BabeBlockImport<B,E,Block,I,RA,PRA> as substrate_consensus_common::block_import::BlockImport<Block>>::import_block
Nov 23 16:49:59 polkadot-london polkadot[17082]:   18: substrate_consensus_common::import_queue::import_single_block
Nov 23 16:49:59 polkadot-london polkadot[17082]:   19: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 23 16:49:59 polkadot-london polkadot[17082]:   20: <futures_util::future::then::Then<Fut1,Fut2,F> as core::future::future::Future>::poll
Nov 23 16:49:59 polkadot-london polkadot[17082]:   21: <futures_util::future::poll_fn::PollFn<F> as core::future::future::Future>::poll
Nov 23 16:49:59 polkadot-london polkadot[17082]:   22: futures_executor::thread_pool::PoolState::work
Nov 23 16:49:59 polkadot-london polkadot[17082]:   23: std::sys_common::backtrace::__rust_begin_short_backtrace
Nov 23 16:49:59 polkadot-london polkadot[17082]:   24: std::panicking::try::do_call
Nov 23 16:49:59 polkadot-london polkadot[17082]:   25: __rust_maybe_catch_panic
Nov 23 16:49:59 polkadot-london polkadot[17082]:              at src/libpanic_unwind/lib.rs:80
Nov 23 16:49:59 polkadot-london polkadot[17082]:   26: core::ops::function::FnOnce::call_once{{vtable.shim}}
Nov 23 16:49:59 polkadot-london polkadot[17082]:   27: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 23 16:49:59 polkadot-london polkadot[17082]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 23 16:49:59 polkadot-london polkadot[17082]:   28: <alloc::boxed::Box<F> as core::ops::function::FnOnce<A>>::call_once
Nov 23 16:49:59 polkadot-london polkadot[17082]:              at rustc/4560ea788cb760f0a34127156c78e2552949f734/src/liballoc/boxed.rs:922
Nov 23 16:49:59 polkadot-london polkadot[17082]:       std::sys_common::thread::start_thread
Nov 23 16:49:59 polkadot-london polkadot[17082]:              at src/libstd/sys_common/thread.rs:13
Nov 23 16:49:59 polkadot-london polkadot[17082]:       std::sys::unix::thread::Thread::new::thread_start
Nov 23 16:49:59 polkadot-london polkadot[17082]:              at src/libstd/sys/unix/thread.rs:79
Nov 23 16:49:59 polkadot-london polkadot[17082]:   29: start_thread
Nov 23 16:49:59 polkadot-london polkadot[17082]:   30: __clone
Nov 23 16:49:59 polkadot-london polkadot[17082]: Thread 'import-queue-worker-0' panicked at 'Storage root must match that calculated.', /home/joserabasso/.cargo/git/checkouts/substrate-7e08433d4c370a21/f44873d/paint/executive/src/lib.rs:292
Nov 23 16:49:59 polkadot-london polkadot[17082]: This is a bug. Please report it at:
Nov 23 16:49:59 polkadot-london polkadot[17082]:         https://github.com/paritytech/polkadot/issues/new
Nov 23 16:49:59 polkadot-london polkadot[17082]: 2019-11-23 16:49:59 Block import error:
Nov 23 16:49:59 polkadot-london polkadot[17082]: Execution(Wasmi(Trap(Trap { kind: Unreachable })))
Nov 23 16:49:59 polkadot-london polkadot[17082]: Hash: given=98c26b3d8143dcbba732863ea445b69662a2b102b3700dea694d0e5035e77f8f, expected=1f645d2a9efb24b04b19ecadf23335f3edf1d9b637dbe2a9ad056cb514e9b1f3

**Comment by BCpowerup** [comment] 2019-11-23 17:00
let me know how can i be of more help. on reboot all went to normal.

**Comment by gavofyork** [comment] 2019-12-04 10:44
@arkpar I guess this is the caching issue?

**Comment by gavofyork** [comment] 2019-12-04 10:55
Duplicate of #582

**Closed by gavofyork** 2019-12-04 10:55 UTC
Labels: F0-consensus
